### PR TITLE
settings | Fixed Name Typo

### PR DESCRIPTION
**Pull request by NajmAjmal**
Made Pi Apps -> Pi-Apps.
Now it is more consistent.

### CODE REVIEW

**Comment by theofficialgman** [comment]
actually its not a typo on this only makes it inconsistent. 
all our .desktop files from the install scripts have the name "Pi Apps". https://github.com/Botspot/pi-apps/blob/master/install

even though I do think that they should probably all be "Pi-Apps" personally

**Comment by theofficialgman** [comment]
@Botspot you missed the place that this PR actually covered. The settings script. Might be others.

**Comment by Botspot** [comment]
> @Botspot you missed the place that this PR actually covered. The settings script. Might be others.

Look more closely at that commit again. I made changes until `grep -r 'Name=Pi Apps' ~/pi-apps` returned nothing but matches from the update folder.

**Comment by theofficialgman** [comment]
Oh I must have missed it. I didn't see settings in the commit before. My bad.

**Pull request closed without merging**
