### PR TITLE
Update Blockbench link

### PR DESCRIPTION
**Pull request by cycool29**

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
Thanks! Could you check other apps that download from raspbian-addons?

**Comment by cycool29** [comment]
> Thanks! Could you check other apps that download from raspbian-addons please?

Only Blockbench and Freetube are downloaded from raspbian-addons in pi-apps, and both of them were updated to the new link.

**Comment by Botspot** [comment]
> Thanks! Could you check other apps that download from raspbian-addons please?

Fortunately it's really easy to do this. You can go to Pi-Apps -> Search button -> only search scripts, and then enter a search term like `raspbian-addons`.

**Comment by Itai-Nelken** [comment]
> > Thanks! Could you check other apps that download from raspbian-addons please?
> 
> Fortunately it's really easy to do this. You can go to Pi-Apps -> Search button -> only search scripts, and then enter a search term like `raspbian-addons`.

I didn't know that!

**Pull request merged**
