### PR TITLE
obs-studio: add cef support (bullseye)

### PR DESCRIPTION
**Pull request by ryanfortner**
I'll be working on adding this to all the debs over the weekend.

resolves https://github.com/Botspot/pi-apps/issues/1698

### CODE REVIEW

**Comment by theofficialgman** [comment]
no @ryanfortner I wanted to list it as closes, because when this PR is merged, then that issues automatically gets closed

**Comment by ryanfortner** [comment]
> no @ryanfortner I wanted to list it as closes, because when this PR is merged, then that issues automatically gets closed
> 
> any of these keywords will trigger that
> 
> ```
> close
> closes
> closed
> fix
> fixes
> fixed
> resolve
> resolves
> resolved
> ```

Oh cool, I didn't know that was a feature! Thanks

**Comment by ryanfortner** [comment]
just finished both bullseye debs.

For Buster, I don't have any spare SD cards at the moment, nor do I have the time to set up a vdesktop. I won't be able to compile buster debs for a little while.

is it ok if I go ahead and merge this for now?

**Comment by theofficialgman** [comment]
in the future, can you compile using the latest OBS tagged release version instead of the master branch directly?

@ryanfortner can you send your OBS log? help -> logfiles -> upload current logfile.
I'd like to verify that everything is working. Previous releases we have had multiple users saying that t he libx264 binary from obs fails to load and I want to see if its at least loading on your system

**Comment by theofficialgman** [comment]
also I would appreciate if you would share the instructions/commands you used to make the deb.
I know how to compile and install with `sudo make install` but how did you make a deb?

**Comment by ryanfortner** [comment]
> also I would appreciate if you would share the instructions/commands you used to make the deb (so others can do so in the future). I know how to compile and install with `sudo make install` but how did you make a deb?

What I like to do is follow the instructions from [here](https://github.com/obsproject/obs-studio/wiki/build-instructions-for-linux) to build from source, but I *don't* run sudo make install.

then use `checkinstall` to create an initial deb (you can install it with sudo apt install checkinstall). on this step, I leave all the values as default because I'll be modifying the package later.

```
sudo checkinstall --install=no
```
then I simply unpack the deb: 
```
dpkg -R checkinstall_deb_file.deb unpacked-deb-directory
```
and now you can modify the DEBIAN/control file inside the unpacked-deb-directory to its appropriate values. then repackage the deb and done. 
```
dpkg --build unpacked-deb-directory
```

**Comment by ryanfortner** [comment]
> in the future, can you compile using the latest OBS tagged release version instead of the master branch directly?

Sure, I will try to. I've been using the `master` branch because using git with --recursive you can download all the components obs needs without cloning them all separately.

> @ryanfortner can you send your OBS log? help -> logfiles -> upload current logfile. I'd like to verify that everything is working. Previous releases we have had multiple users saying that t he libx264 binary from obs fails to load and I want to see if its at least loading on your system

https://obsproject.com/logs/T38LNi-oeWMQh5Ug

**Comment by theofficialgman** [comment]
> Sure, I will try to. I've been using the `master` branch because using git with --recursive you can download all the components obs needs without cloning them all separately.

you can do this with a tag or commit hash as well, its what is done for the multimc script

this is what I have found to be foolproof
```
git clone --recursive gitlocation
cd gitlocation
git checkout --recurse-submodules desired-branch
git pull --recurse-submodules
git checkout --recurse-submodules commit-hash-or-tag
```

**Comment by Itai-Nelken** [comment]
> [ ... ] using git with --recursive you can download all the components obs needs without cloning them all separately.
> 

You can download them later as well with `git submodule update --init`.

**Comment by theofficialgman** [comment]
> https://obsproject.com/logs/T38LNi-oeWMQh5Ug

ok, it is working on your system. so thats good to know

**Comment by ryanfortner** [comment]
Ready for merge?

**Comment by theofficialgman** [comment]
I'm fine with a merge, though it will push an unnecessary update to buster users who won't get anything new
@Botspot what do you think? merge now?

**Comment by Botspot** [comment]
> I'm fine with a merge, though it will push an unnecessary update to buster users who won't get anything new @Botspot what do you think? merge now?

Sure. As long as this doesn't break buster, there is little point to porting ***new*** features back to Buster.

**Comment by theofficialgman** [comment]
> Sure. As long as this doesn't break buster, there is little point to porting _**new**_ features back to Buster.

its just updating the debs for bullseye 32 and 64bit to include browser dock/source support in OBS
the buster debs are untouched so nothing will change

**Pull request merged**
