### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by mobilegmYT**

### CODE REVIEW

**Comment by mobilegmYT** [comment]
@Botspot OwO

**Comment by Botspot** [comment]
Why were three lines deleted?

**Comment by Botspot** [comment]
And, please remove the lines pertaining to updating an app's version number.

**Review by CleanMachine1 — APPROVED** [review]

**Comment by mobilegmYT** [comment]
> Why were three lines deleted?

Hm? Nothing got deleted.
image

**Comment by Botspot** [comment]
> Hm? Nothing got deleted.

My bad. It appeared that way due to how the minus signs were being displayed **in red**.
2021-06-28-081221_1366x768_scrot

**Comment by mobilegmYT** [comment]
@Botspot Alright, pushed new commit

**Pull request merged**
