### PR TITLE
Replace yad install by yad appimage

### PR DESCRIPTION
**Pull request by pi-dev500**

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
interesting! I would add the .AppImage file extension to them so people know what they are.

**Comment by pi-dev500** [comment]
Done now.

**Comment by Itai-Nelken** [comment]
did you test this?

**Comment by pi-dev500** [comment]
I have tested the armhf appimage but for 64 bits,I can't test.

**Comment by Botspot** [comment]
> Replace yad install by yad appimage

I don't have a problem with doing this per se, if there's a good reason, but what _is_ your reason for preferring a yad appimage over an apt package?

**Comment by pi-dev500** [comment]
It is faster and simplest to install. and that can be also more portable after some code modifications.

**Comment by pi-dev500** [comment]
I have tested the arm64 appimage whith debian-buster-64 installed with Pi-Gro. That works also well expectly some gtk-warnings.

**Comment by Botspot** [comment]
I've decided not to add this.

1. All Botspot apps use YAD. Nobody has had a problem with using apt to install yad.
2. AppImages sometimes have issues on RPiOS.

In my opinion, the potential benefit is too small, and the potential risks are too high, to consider merging this.

**Pull request closed without merging**
