### PR TITLE
add peazip app

### PR DESCRIPTION
**Pull request by ryanfortner**
Closes https://github.com/Botspot/pi-apps/issues/1865

### CODE REVIEW

**Comment by Botspot** [comment]
I think `install` needs to be renamed to `install-64`, as I justr tried this on my armhf system and the error was `Nothing matches io.github.peazip.PeaZip in remote flathub`

**Comment by ryanfortner** [comment]
> I think `install` needs to be renamed to `install-64`, as I just tried this on my armhf system and the error was `Nothing matches io.github.peazip.PeaZip in remote flathub`

Done. Thanks for noticing that @Botspot .

I think this is ready to be merged. I've tested it on ubuntu 20.04 arm64 and afterburnermod, as well as rpios buster 64 and all work flawlessly.

**Comment by theofficialgman** [comment]
looks good and I think its fine to merge (worked fine on bionic when I tested it)

but just a thought for the future, since this is "bascially" a "package app" do you think we should add a specifically script name for for flatpaks? we have install(-32/-64) and package, but maybe we should add a flatpak

just a thought incase pi-apps starts getting lots of flatpaks

**Comment by Botspot** [comment]
> looks good and I think its fine to merge (worked fine on bionic when I tested it). the only thing I noticed is the gtk theme doesn't match my theme, but thats a flatpak issue in general
> 
> but just a thought for the future, since this is "bascially" a "package app" do you think we should add a specifically script name for for flatpaks? we have install(-32/-64) and package, but maybe we should add a flatpak
> 
> just a thought incase pi-apps starts getting lots of flatpaks

The reason for package-apps was two-fold: first it allowed for more efficient app-creation, but also it allowed for additional features that would be impossible with script-type apps.
With the limited nature of package-apps, it becomes trivial to check which ones are already installed, thereby setting app status accordingly. This is handled by `refresh_pkgapp_status`.

A similar argument could be made for flatpak apps: make a flatpak-app type so it's possible to detect which ones are installed with a similar `refresh_flatapp_status` function. We will have to discuss this and decide if the additional complexity of a third app_type is worth it. For now, flatpak is less prevalent than apt.

**Pull request merged**
