### PR TITLE
Make box86 work after installed

### PR DESCRIPTION
**Pull request by heavygabriel**

### CODE REVIEW

**Comment by Botspot** [comment]
@Itai-Nelken I thought your box86 deb already refreshed `systemd-binfmt`?

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken I thought your box86 deb already refreshed `systemd-binfmt`?

@Botspot yes, it does.

**Comment by Botspot** [comment]
> > @Itai-Nelken I thought your box86 deb already refreshed `systemd-binfmt`?
> 
> @Botspot yes, it does.

Any idea how/why [this](https://github.com/Botspot/pi-apps/issues/383#issuecomment-803185874) happened?

**Comment by Itai-Nelken** [comment]
> Any idea how/why [this](https://github.com/Botspot/pi-apps/issues/383#issuecomment-803185874) happened?

no, but I'll try and see if I can get what deb @heavygabriel was using, maybe its broken?

**Comment by Itai-Nelken** [comment]
@Botspot I found the issue and it has nothing to do with my debs: the steam install script is stilllusing pales automated builds.
Screen Shot 2021-03-20 at 5 41 47 PM

**Comment by Botspot** [comment]
Okay, all apps now use the Box86 app (which is Itai's), instead of box86-updater.

This change effectively solves the original problem.

**Pull request closed without merging**
