### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by theofficialgman**
change changelog to have separate lists for new apps, and other stuff (makes updating easier through scripting). 
you can run this from the apps folder to generate it
```
for d in */ ; do  git log --follow --format=%ad --date=format:'%m/%d/%Y' "$d" | tail -1 | tr -d '\n'; echo '**'" Added ${d///} app";  done | sort -n -t"/" -k3 -k1 -k2 | sed -e 's/^/- **/'
```

### CODE REVIEW

**Comment by theofficialgman** [comment]
also sorry for creating this on the Bostpot repo. I generally try to remember to make it on my fork but sometimes I forget and its easier to just spin up a new branch rather than pick it to my fork.

**Comment by Botspot** [comment]
> also sorry for creating this on the Bostpot repo. I generally try to remember to make it on my fork but sometimes I forget and its easier to just spin up a new branch rather than pick it to my fork.

I'm not sure why you consider this bad practice, but I don't have a problem with it at all unless there is some downside that I am not aware of.

**Comment by theofficialgman** [comment]
> I'm not sure why you consider this bad practice, but I don't have a problem with it at all unless there is some downside that I am not aware of.

I consider it bad practice personally because I'm making branches in your own repo, not my own. also git clone/pulls will see these new branches as potential targets. Glad to hear you don't mind though

**Comment by Botspot** [comment]
> I consider it bad practice personally because I'm making branches in your own repo, not my own. also git clone/pulls will see these new branches as potential targets. Glad to hear you don't mind though

If Pi-Apps receives more improvements because you use time-saving measures, I won't complain too much. 🤣

...And it looks like a robot just took over @mobilegmYT's old job.

> ```
> for d in */ ; do  git log --follow --format=%ad --date=format:'%m/%d/%Y' "$d" | tail -1 | tr -d '\n'; echo '**'" Added ${d///} app";  done | sort -n -t"/" -k3 -k1 -k2 | sed -e 's/^/- **/'
> ```

**Comment by mobilegmYT** [comment]
😭 please i need my salary papi

**Pull request merged**
