### PR TITLE
why so complicated

### PR DESCRIPTION
**Pull request by srini-pro**
just
sudo apt update
 sudo apt install snap
sudo snap install snap-store

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
the snap core is needed, and a restart is needed, so @techcoder20 found a way around it.
read #171

**Comment by techcoder20** [comment]
There were also a problem where the desktop entry would appear in Twister OS and not in Raspberry Pi OS, so botspot suggested using a symlink between two folders which resulted in more code

**Comment by Botspot** [comment]
> why so complicated

Well, now you know! This is how people get smart, by asking questions. Thanks for asking. :)

**Comment by srini-pro** [comment]
thanks a lot

**Pull request closed without merging**
