### PR TITLE
Update Etcher to 1.5.116 (32bit)

### PR DESCRIPTION
**Pull request by chunky-milk**
I had 64bit compile issues but I'm working on it, for now just 32bit

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
I already released etcher 1.5.116 in my repo a few minutes ago: https://github.com/Itai-Nelken/Etcher-arm-32-64/releases/tag/v1.5.116

Didn't come to updating the scripts yet though.

**Comment by chunky-milk** [comment]
@Itai-Nelken Ok great, I'll just close this now

**Comment by Itai-Nelken** [comment]
@chunky-milk your apt repo is a great idea!
Also you can update the scripts to download my latest release if you wan't. I'll do it later today or tomorrow if you don't.

**Comment by Botspot** [comment]
> @chunky-milk your apt repo is a great idea!
> Also you can update the scripts to download my latest release if you wan't. I'll do it later today or tomorrow if you don't.

@Itai-Nelken Hey could you check your discord?

**Pull request closed without merging**
