### PR TITLE
Force MCPI update to build 50

### PR DESCRIPTION
**Pull request by mobilegmYT**

### CODE REVIEW

**Comment by Botspot** [comment]
How many of these changes are actually noticeable by end-users?

**Comment by mobilegmYT** [comment]
> How many of these changes are actually noticeable by end-users?

What do you mean?

**Comment by mobilegmYT** [comment]
Well he removed and added some important code, and removed something to do with root, but still better to update than to not 🤷‍♂️

**Comment by Botspot** [comment]
> > How many of these changes are actually noticeable by end-users?
> 
> What do you mean?

I mean, what changes have been made between version 48 and 50? Significant changes, or severe bugs fixed, necessitating a Pi-Apps update?

Or one mere correction to a typo?

**Comment by Botspot** [comment]
> Well he removed and added some important code, and removed something to do with root, but still better to update than to not

Okay. I'll push it then.

**Pull request merged**
