### PR TITLE
Update libboost-* libs to latest version 1.74.0 in hirsute in box86 install-64

### PR DESCRIPTION
**Pull request by Jai-JAP**

### CODE REVIEW

**Comment by Botspot** [comment]
@Itai-Nelken Could you try reviewing this? (I don't use ubuntu)

**Comment by Itai-Nelken** [comment]
Yes, of course. But it will jave to be to tomorrow.

**Comment by Itai-Nelken** [comment]
The package `libraspberrypi0:armhf` has to be removed as it conflicts with the 64bit version, so this PR is a great opportunityto do it.

**Comment by Jai-JAP** [comment]
> The package `libraspberrypi0:armhf` has to be removed as it conflicts with the 64bit version, so this PR is a great opportunityto do it.

Is it required for ubuntu hirsute only or for all distros

**Comment by Itai-Nelken** [comment]
> > The package `libraspberrypi0:armhf` has to be removed as it conflicts with the 64bit version, so this PR is a great opportunityto do it.
> 
> Is it required for ubuntu hirsute only or for all distros

I tested it on hirsute only, but I guess that for all distros that install the 64bit version.
I say remove it only from hisrute because I don't think that groovy has it.

**Comment by Itai-Nelken** [comment]
Looks good to me, but unfortunately I won't be able to test until next week. So if anyone running a fresh Ubuntu 21.04 install on the rpi can test, it will help a lot.

**Comment by Jai-JAP** [comment]
I changed dependency pulseaudio:armhf pulseaudio-utils:armhf to arm64 ones in install-64 to improve support for all apps as armhf version conflicts with arm64 version

**Comment by Itai-Nelken** [comment]
looks good to me, but still needs testing.

**Comment by Jai-JAP** [comment]
Tested Zoom on box86 arm64 with pulseaudio instead of pulseaudio:arm64. Works well.

**Review by Itai-Nelken — APPROVED** [review]

**Comment by Itai-Nelken** [comment]
Thanks @Jai-JAP!

**Pull request merged**
