### PR TITLE
Etcher install scripts always download the latest version.

### PR DESCRIPTION
**Pull request by Itai-Nelken**
instead of having to update the link every time I compile and package a new version.
@Botspot don't merge yet,  I still want to be 100% sure it works.

### CODE REVIEW

**Comment by Botspot** [comment]
I'm not sure what I think of this.

On the one hand, you're right, it will slightly reduce the workload whenever Etcher receives an update. But on the other hand, Etcher would never auto-update once installed.

Auto-updating in this manner basically circumvents Pi-Apps's updating approach.

I think the occasional minute or two taken to update a url in the install script, consequently triggering an update for everyone, is the best way to go.

**Comment by Itai-Nelken** [comment]
ok, I have no problem changing the link. I just thought it might be better seeing as thats the way with the discord app.

**Comment by Botspot** [comment]
> ok, I have no problem changing the link. I just thought it might be better seeing as thats the way with the discord app.

That's because spacingbat3 updated discord so often... the updates for it got annoyingly frequent.

There's a balance, you've got to admit. ;)

**Comment by Itai-Nelken** [comment]
>There's a balance, you've got to admit. ;)

you are right.

**Pull request closed without merging**
