### PR TITLE
Improve updater script to run faster

### PR DESCRIPTION
**Pull request by Botspot**
Once merged, this will solve issue https://github.com/Botspot/pi-apps/issues/1436

Making major changes to the `updater` script is risky, because if anything breaks then many users will be stranded with an outdated Pi-Apps installation for 3 months. (before the forced updater in the `manage` script kicks in)

**Testers wanted.**

### CODE REVIEW

**Comment by Botspot** [comment]
Tagging a few people:
@theofficialgman @cycool29 @Itai-Nelken @mobilegmYT

**Comment by theofficialgman** [comment]
> Making major changes to the `updater` script is risky, because if anything breaks then many users will be stranded with an outdated Pi-Apps installation for 3 months. (before the forced updater in the `manage` script kicks in)

now might be a good time to change that as well... do you think it would be a beneficial to put something here to force the "3 month update", if this command returns with an error code thats not 0 or 1 (since the error function can make it exit with 1)? 
syntax errors in the script will exit with an error code of 2
https://github.com/Botspot/pi-apps/blob/73cf1d93cf657091fce7929047f69e89f3ba9939/gui#L725

syntax errors in the script will exit with an error code of 2

**Comment by Sussy-OS** [comment]
May I help test this, @Botspot ?

**Comment by Botspot** [comment]
> May I help test this, @Botspot ?

Sure, but I think I'm going to merge this today as I've used it without incident.

**Comment by Botspot** [comment]
These changes were made with commit https://github.com/Botspot/pi-apps/commit/53cc33b3c5f4f1fd772ba8de9c782b0430cdaf86.

**Pull request closed without merging**
