### PR TITLE
auto update Vivaldi

### PR DESCRIPTION
**Pull request by cobalt2727**
let apt handle things instead

### CODE REVIEW

**Comment by Botspot** [comment]
First, there is no need to run `sudo apt update` - the `install_packages` command does that for you.
Second, I'm pretty sure that arm64 Vivaldi is in beta and is unavailable in the repository.
Third, 32-bit Vivaldi already self-configured itself to automatically update. (During installation, the deb file would initialize the repository)

**Comment by cycool29** [comment]
> Second, I'm pretty sure that arm64 Vivaldi is in beta and is unavailable in the repository.

There is `stable` version of Vivaldi arm64 in its repository.

image

**Comment by cobalt2727** [comment]
Apparently arm64 support is a recent thing.

**Comment by craigevil** [comment]
The Vivaldi repo now supports arm32/arm64. I tried it after I saw they had the arm64 version on the download page.
policy vivaldi-stable
vivaldi-stable:
  Installed: 4.3.2439.71-1
  Candidate: 4.3.2439.71-1
  Version table:
 *** 4.3.2439.71-1 500
        500 http://repo.vivaldi.com/stable/deb stable/main arm64 Packages
Both vivaldi-stable and vivaldi-snapshot are available.

**Pull request merged**
