### PR TITLE
Use instant binary instead of adding adoptium repo

### PR DESCRIPTION
**Pull request by cycool29**
Just want to make the installation simple, and easy for uninstallation.

### CODE REVIEW

**Comment by Botspot** [comment]
@theofficialgman

**Comment by theofficialgman** [comment]
no @cycool29 this is exactly what we are trying to avoid
the temurin repo is up now. all scripts will be using it if they need functional java
we don't want each and every script to download its own java version, taking up extra valuable space on a users install

making the number of lines of code less does not make it simple

**Comment by theofficialgman** [comment]
for example: now pi-apps has (or will soon have) 4 applications all that need working java versions
Unciv, Minecraft Java, Minecraft Java MultiMC5, and Minecraft Java Server.

if each of these scripts installed their own java versions in their own folders instead of using the apt repo, the size of the JDK installed would be 4X (which is significant when the JRE is about 80MB, and JDK is over 300MB)

**Comment by cycool29** [comment]
What I think is the GPG key is not deleted when uninstalling. 
Since `remove_repofile_if_unused` is here, that problem is solved.

**Pull request closed without merging**
