### PR TITLE
Change Bedrock uninstall

### PR DESCRIPTION
**Pull request by mobilegmYT**
just in case a user wants all data gone. I added a failsafe and also tested the code.

### CODE REVIEW

**Comment by Botspot** [comment]
During an update, we don't want a user-input holding the update process up if we can't help it. So let's work out a middle-ground.

@mobilegmYT, could you figure out exactly which directory is responsible for holding the minecraft world and configuration? Let's keep that. Everything else non-essential can be removed without asking.

**Comment by mobilegmYT** [comment]
> During an update, we don't want a question holding the process up if we can't help it. So let's work out a middle-ground.
> 
> @mobilegmYT, could you figure out exactly which directory is responsible for holding the minecraft world and configuration? Let's keep that. Everything else non-essential can be removed without asking.

Alright, only configs and game files are kept now.

**Comment by Botspot** [comment]
Looks like we still need to get rid of the dialog.

**Comment by Botspot** [comment]
Why is the dialog still there?

**Comment by mobilegmYT** [comment]
> Why is the dialog still there?

wdym?

**Pull request merged**
