### PR TITLE
fix critical Zoom 64-bit installation error

### PR DESCRIPTION
**Pull request by cobalt2727**
also modified dependencies to be 1:1 with the 32-bit install script

### CODE REVIEW

**Comment by cobalt2727** [comment]
tester report from github:

```ruby
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 93281 files and directories currently installed.)

Apt finished.
Package installation complete.
E: Unsupported file /home/pi/pi-apps-c08187a2.deb given on commandline
Apt finished.
Failed to install the packages!
APT reported these errors:
E: Unsupported file /home/pi/pi-apps-c08187a2.deb given on commandline
E: Unsupported file /home/pi/pi-apps-c08187a2.deb given on commandline
```

**Comment by Botspot** [comment]
Looks like an issue with the `|` operator - bash is interpreting it as a pipe.

**Comment by cobalt2727** [comment]
shouldn't we still have it attempting to install `libxcb` and `pulseaudio` dependencies for both tries though?

**Comment by Botspot** [comment]
> shouldn't we still have it attempting to install `libxcb` and `pulseaudio` dependencies for **both tries** though?

That's not what is happening here. The `install_packages` command is only being run once. However, in this case we have a "`|`" operator between two package names: `libturbojpeg0` and `libturbojpeg`. These are two different packages - some systems have the former while others have the latter.
This `|` functionality was added in PR #669.

**Pull request merged**
