### PR TITLE
Update Zoom install-64

### LINKED ISSUE #710: install-64 fails for box86 and Zoom
installing Zoom I get:
```
Installing Zoom with install-64 script
Running pkg-install...
Waiting until APT locks are released... Done
Running sudo apt update...

Creating dummy deb...
dpkg-deb: building package 'pi-apps-c08187a2' in '/home/pi/pi-apps-c08187a2.deb'.

Installing dummy deb...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pi-apps-c08187a2 : Depends: cmake:armhf
E: Unable to correct problems, you have held broken packages.

Apt finished.
Failed to install the packages!
APT reported these errors:
E: Unable to correct problems, you have held broken packages.

Failed to install Zoom with install-64 script!
```
and box86:
```
Installing Box86 with install-64 script
armhf arcitecture already added...
Running pkg-install...
Waiting until APT locks are released... Done
Running sudo apt update...

Creating dummy deb...
dpkg-deb: building package 'pi-apps-5f3374a7' in '/home/pi/pi-apps-5f3374a7.deb'.

Installing dummy deb...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pi-apps-5f3374a7 : Depends: libraspberrypi0:armhf
                    Depends: libsdl1.2debian:armhf
                    Depends: libsdl2-2.0-0:armhf
                    Depends: libsdl1.2-dev:armhf
                    Depends: libsdl-mixer1.2:armhf
                    Depends: libsdl2-net-2.0-0:armhf
                    Depends: libsdl2-image-2.0-0:armhf
                    Depends: libsmpeg0:armhf
                    Depends: libavcodec58:armhf
                    Depends: libavformat58:armhf
                    Depends: libsdl2-mixer-2.0-0:armhf
E: Unable to correct problems, you have held broken packages.

Apt finished.
Failed to install the packages!
APT reported these errors:
E: Unable to correct problems, you have held broken packages.

Failed to install Box86 with install-64 script!
```
```
pi@blinky:~/src $ uname -a
Linux blinky 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
```
thank you :-)

### PR DESCRIPTION
**Pull request by Jai-JAP**
Update Zoom install-64 to fix #710

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
Thanks @Jai-JAP!
This is tested, right?

**Comment by Jai-JAP** [comment]
Only on ubuntu 21.04

**Comment by Jai-JAP** [comment]
I am gonna test it on RPiOS arm64

**Comment by Jai-JAP** [comment]
This is now tested and works on RPiOS, Ubuntu 20.04, 20.10 & 21.04

**Comment by Itai-Nelken** [comment]
Great, thanks!

**Pull request merged**
