### PR TITLE
print error and exit if install script is run as root

### PR DESCRIPTION
**Pull request by Itai-Nelken**
#695 
and should fix cases like #694

### CODE REVIEW

**Comment by Kirill2006183** [comment]
> [# 695](https://github.com/Botspot/pi-apps/pull/695)
> и должен исправить такие случаи, как [# 694](https://github.com/Botspot/pi-apps/issues/694)

The question is solved I had to download the program file sudo apt install file only without root and started me

**Comment by Kirill2006183** [comment]
> [# 695](https://github.com/Botspot/pi-apps/pull/695)
> и должен исправить такие случаи, как [# 694](https://github.com/Botspot/pi-apps/issues/694)

It starts with and without root without errors

**Comment by Kirill2006183** [comment]
> [# 695](https://github.com/Botspot/pi-apps/pull/695)
> и должен исправить такие случаи, как [# 694](https://github.com/Botspot/pi-apps/issues/694)

It was necessary to install the sudo apt install file

**Comment by Botspot** [comment]
Perhaps [this technique](https://stackoverflow.com/a/28776100) would be better? We need the script to detect `sudo` usage, *as well as* `root` usage.

**Comment by Itai-Nelken** [comment]
It now uses `-id -u`, I tested and it does work: the error is printed when running with `sudo` and when running as the root user without `sudo`.

**Comment by Itai-Nelken** [comment]
ready to merge in my opinion. what do you say @Botspot?

**Pull request merged**
