### PR TITLE
Hopefully fix problem phoenixbyrd had with internet not working after uninstalling lokinet

### PR DESCRIPTION
**Pull request by Itai-Nelken**
## not tested
Uninstalls `lokinet-bin`

### CODE REVIEW

**Review by necro-nemesis — COMMENTED** [review]
Tested it but there's a typo in line 12 `sudo apt purge lokinet-bin - y ` an extra space between "-" and the "y". Should read `sudo apt purge lokinet-bin -y || error "Failed to uninstall \"lokinet-bin\"!"`

**Comment by Itai-Nelken** [comment]
Oops, fixed it. Should work now.
Can you please test it @necro-nemesis?

**Comment by necro-nemesis** [comment]
```The following packages will be REMOVED:
  lokinet-bin*
0 upgraded, 0 newly installed, 1 to remove and 98 not upgraded.
After this operation, 2,212 kB disk space will be freed.
(Reading database ... 168973 files and directories currently installed.)
Removing lokinet-bin (0.8.4-2~deb10) ...
Processing triggers for man-db (2.8.5-2) ...

Uninstalled Lokinet successfully.

Closing in 30 seconds.
```
Works fine.

**Comment by Itai-Nelken** [comment]
Thanks @necro-nemesis.

**Comment by Botspot** [comment]
Thanks guys.

It's wonderful to come back from a hard day and long night (trying to track down my friend who ran away from home), and see others taking care of business while I was away.

**Comment by necro-nemesis** [comment]
Thanks for giving everyone a place to gather together all of our apps and participate. I'm guessing this was a cat or dog? I hope you find them soon.

**Comment by Botspot** [comment]
> I'm guessing this was a cat or dog? I hope you find them soon.

No. He was about my age. He drove his truck away in the middle of the night and the family is devastated.  
I've been helping the family check his browsing history and recover various clues as to why he left. We're pretty sure he drove >900 miles away, based on IP addresses in various sign-in logs. The whole situation has been very stressful for all involved, and I've gone to bed around 2AM for the past 3 nights.

**Comment by necro-nemesis** [comment]
Stressful times. Hopefully he just needs some breathing space. Thankfully you are able to add some insight to his potential whereabouts to all who must be very concerned. Happens to the best of us. Sometimes your plate is just too full.

**Pull request merged**
