### PR TITLE
Remove support for buster in Zoom/install64 as box86 does not support it

### PR DESCRIPTION
**Pull request by Jai-JAP**
Remove support for buster as box86 does not support it

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
lets change it to box64 then. I'll merge this for now though.

**Comment by Itai-Nelken** [comment]
box64 works on all of the arm64 distros I have tried, and it runs zoom better than box86!

**Comment by Jai-JAP** [comment]
Okay

**Comment by Jai-JAP** [comment]
I have not tested box64 yet

**Comment by Itai-Nelken** [comment]
I did test it with box64, everything works including sound!

**Pull request merged**
