### PR TITLE
use | in obs install_packages to avoid apt false * autocomplete

### PR DESCRIPTION
**Pull request by theofficialgman**

### CODE REVIEW

**Comment by Botspot** [comment]
I think OBS requires more than one `libxcb*` package. Have you tested OBS with these other packages missing?

**Comment by theofficialgman** [comment]
yeah I'm downloading the official deb right now to see what it needs

**Comment by theofficialgman** [comment]
```
libasound2 (>= 1.0.16), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 2.2.0), libatspi2.0-0 (>= 2.9.90), libavcodec58 (>= 7:4.2), libavdevice58 (>= 7:4.0), libavformat58 (>= 7:4.2), libavutil56 (>= 7:4.0), libc6 (>= 2.29), libcairo2 (>= 1.6.0), libcups2 (>= 1.7.0), libcurl4 (>= 7.16.2), libdbus-1-3 (>= 1.9.14), libdrm2 (>= 2.4.38), libegl1, libexpat1 (>= 2.0.1), libfdk-aac1 (>= 0.1.4), libfontconfig1 (>= 2.12.6), libfreetype6 (>= 2.2.1), libgbm1 (>= 17.1.0~rc2), libgcc-s1 (>= 3.0), libglib2.0-0 (>= 2.39.4), libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125, libjansson4 (>= 2.3), libluajit-5.1-2 (>= 2.0.4+dfsg), libmbedcrypto3 (>= 2.13), libmbedtls12 (>= 2.13), libmbedx509-0 (>= 2.0), libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.22), libpango-1.0-0 (>= 1.14.0), libpci3 (>= 1:3.5.1), libpulse0 (>= 0.99.1), libpython3.8 (>= 3.8.2), libqt5core5a (>= 5.12.2), libqt5gui5 (>= 5.9.0~beta) | libqt5gui5-gles (>= 5.9.0~beta), libqt5network5 (>= 5.0.2), libqt5svg5 (>= 5.6.0~beta), libqt5widgets5 (>= 5.11.0~rc1), libqt5xml5 (>= 5.0.2), libspeexdsp1 (>= 1.2~beta3.2-1), libstdc++6 (>= 9), libswresample3 (>= 7:4.0), libswscale5 (>= 7:4.0), libudev1 (>= 183), libv4l-0 (>= 0.5.0), libwayland-client0 (>= 1.9.91), libwayland-egl1 (>= 1.15.0), libx11-6 (>= 2:1.4.99.1), libx11-xcb1 (>= 2:1.6.9), libx264-155, libxcb-randr0 (>= 1.12), libxcb-shm0, libxcb-xfixes0, libxcb-xinerama0, libxcb1 (>= 1.9.2), libxcomposite1 (>= 1:0.4.5), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxkbcommon0 (>= 0.5.0), libxrandr2, libxshmfence1, zlib1g (>= 1:1.1.4), qtwayland5
```
from the official deb

**Comment by Botspot** [comment]
Ready for merge?

**Comment by theofficialgman** [comment]
waiting for confirmation from the user in discord

**Comment by theofficialgman** [comment]
@Botspot quashed changes into one, ready for merge
user said this issue was unfixable https://github.com/Botspot/pi-apps/issues/1353 except you can go to advanced encoder settings and enable the ffmpeg encoder to record from there 🤷🏻‍♂️

**Comment by frogro** [comment]
Hi @theofficialgman is obs working again on Pi4?

**Comment by theofficialgman** [comment]
@frogro I don't have a pi. and have asked users multiple times to post their logfile when starting OBS

refer to https://github.com/Botspot/pi-apps/issues/1353#issuecomment-1097477408

nothing can or will be done until this has been done

**Pull request merged**
