### PR TITLE
Translated the README to Simplified Chinese

### PR DESCRIPTION
**Pull request by hmsjy2017**

### CODE REVIEW

**Comment by CleanMachine1** [comment]
@mobilegmYT

**Comment by mobilegmYT** [comment]
> @mobilegmYT

I mean I had a look and all the translations look good, just more needs to be translated and also the `To uninstall Pi-Apps` part should say `卸载 Pi-Apps`.

**Comment by Itai-Nelken** [comment]
@hmsjy2017 why did you change the install line link? because raw github links are blocked in China?
@Botspot do you approve?

**Comment by hmsjy2017** [comment]
@Itai-Nelken Because the link of GitHub Raw cannot be accessed normally in China Mainland. So I have to use the CDN link instead.

**Comment by CleanMachine1** [comment]
raw.github is banned in China??
Thats pretty stupid since you can just view the content in a different format..

**Comment by hmsjy2017** [comment]
> raw.github is banned in China??

Without using a proxy or CDN, even accessing GitHub and cloning repositories are not smooth.

**Comment by CleanMachine1** [comment]
I don't think is fair not not supply a full README for a Chinese audience.
Just take your time and complete it for a better experience, there isn't really a time frame for this :smile:

**Comment by CleanMachine1** [comment]
https://en.wikipedia.org/wiki/Censorship_of_GitHub#China very interesting, didn't think the "censorship" would cover programmer things, anyway enough politics and what not :shrug:

**Comment by CleanMachine1** [comment]
@hmsjy2017 I know I said no time frame however I hope you remember this PR, thats all

**Comment by hmsjy2017** [comment]
@CleanMachine1 I know.

**Comment by hmsjy2017** [comment]
@Botspot I have finished translating it.

**Comment by CleanMachine1** [comment]
@Itai-Nelken Maybe take a look and re-pinging @Botspot

**Comment by Itai-Nelken** [comment]
@Botspot

**Comment by hmsjy2017** [comment]
@Botspot

**Comment by Itai-Nelken** [comment]
@Botspot what do you say? I think its good to add more languages to the readme
 @hmsjy2017 could you mention that pi-apps itself isn't available in chinese?

**Comment by mobilegmYT** [comment]
Since pi-apps itself does support Chinese I could probably make a secondary video covering it in Chinese

**Comment by Botspot** [comment]
> @Botspot what do you say?

I was hesitant to marge for the following reasons:

- Adding a Chinese README will undoubtly increase the number of Chinese users. This, in turn, will increase us developers' workload.
- While working at the summer camp, I had no way to predict how much **time** I'd have to spend on Pi-Apps. That information is now known.

Now that I know how involved I can still be in Pi-apps, I have no problem merging it.
Is now a good time? Or should we wait for @hmsjy2017 to mention that Pi-Apps doesn't support Chinese itself?

**Comment by Itai-Nelken** [comment]
Let's wait for @hmsjy2017.

**Comment by hmsjy2017** [comment]
There are many words in the README, which may be tiring for non-native English speakers. So I think it is necessary to add some translations. I think that with the Chinese README, even if Pi-Apps does not have a Chinese translation, it will not be too difficult to use.

**Comment by mobilegmYT** [comment]
@Botspot Soo... merge?

**Comment by mobilegmYT** [comment]
agagaggaa

**Comment by theofficialgman** [comment]
pi-apps has changed very significantly since this chinese readme was created, unless someone steps up and wants to maintain a readme for chinese full time, then having an additional outdated chinese readme in addition to the english readme will just be confusing and not helpful

**Pull request closed without merging**
