### PR TITLE
Add MS Teams

### PR DESCRIPTION
**Pull request by cycool29**
Although there is [teams-for-linux](https://github.com/IsmaelMartinez/teams-for-linux) snap and can be installed with `snapd`, I prefer installing MS Teams in Pi-Apps. 

Built with nativefier, tested on armv7l.

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
Electron (what nativefier uses) is basically chromium, but it doesn't have the optimizations rpf made for the pi. so I don't see any advantages to using this webapp over using it in chromium.

**Comment by Botspot** [comment]
> Electron (what nativefier uses) is basically chromium, but it doesn't have the optimizations rpf made for the pi. so I don't see any advantages to using this webapp over using it in chromium.

I recently compared Zoom's PWA in Nativefier vs Chromium. Results: Nativefier loaded the page slightly faster. The video frame-rate and CPU-usage was roughly equivalent in both options. I noticed the incoming video latency was slightly better in Chromium, while the incoming audio latency was better in Nativefier. Both options were laggier than the emulated desktop version of Zoom though.

**Comment by CleanMachine1** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.0.12/teams-for-linux_1.0.12_armv7l.deb 

Whats wrong with this?

**Comment by Botspot** [comment]
> https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.0.12/teams-for-linux_1.0.12_armv7l.deb
> 
> Whats wrong with this?

Wow I didn't know they had ARM builds. The deb installed fine for me.

**Comment by cycool29** [comment]
> https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.0.12/teams-for-linux_1.0.12_armv7l.deb
> 
> Whats wrong with this?

It installed and works fine for me. 
@Botspot Should I change my script to the [deb](https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.0.12/teams-for-linux_1.0.12_armv7l.deb) instead of the current one?

**Comment by Botspot** [comment]
> @Botspot Should I change my script to the [deb](https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v1.0.12/teams-for-linux_1.0.12_armv7l.deb) instead of the current one?

I would, simply because it's a more-mature project. Their bug-fixes will benefit us, and we will have less workload. (as we can redirect users to the teams-for-linux repo)

**Comment by cycool29** [comment]
Updated the script. Tested installing and uninstalling on armv7l. Launch well. 
Also added credits to the creator of teams-for-linux.

**Pull request merged**
