### PR TITLE
Update install

### PR DESCRIPTION
**Pull request by Sussy-OS**
@Botspot Please merge this, to update LineRider. Edit: Actually, I need to wait till [files #23](https://github.com/Pi-Apps/Coders/files/pull/23) is merged

### CODE REVIEW

**Comment by Botspot** [comment]
https://github.com/Pi-Apps/Coders/files/pull/23 has been merged.

**Comment by Sussy-OS** [comment]
> https://github.com/Pi-Apps/Coders/files/pull/23 has been merged.

Okay, @Botspot thanks! Now, can you please merge this, to update the LineRider install, so it will update for any new users?

**Comment by Sussy-OS** [comment]
wait, merge this first: https://github.com/Pi-Apps-Coders/files/pull/24 then merge this

**Comment by Botspot** [comment]
Ready for merge now, as https://github.com/Pi-Apps-Coders/files/pull/24 has been merged?

**Comment by Sussy-OS** [comment]
> Ready for merge now, as [Pi-Apps-Coders/files#24](https://github.com/Pi-Apps-Coders/files/pull/24) has been merged?

Yes, thanks, @Botspot (Sorry for responding late, as my sister was doing her first reconciliation)

**Comment by mobilegmYT** [comment]
ripoff >: |

**Pull request merged**
