### PR TITLE
Update QEMU (again)

### PR DESCRIPTION
**Pull request by Itai-Nelken**
the deb I uploaded was defective...

### CODE REVIEW

**Comment by Botspot** [comment]
:O

**Comment by Botspot** [comment]
Do you mean that anyone who now tries to install QEMU for the first time, it will be defective?

**Comment by Itai-Nelken** [comment]
> Do you mean that anyone who now tries to install QEMU for the first time, it will be defective?

unfortunately yes, dpkg will fail because I accidentally copied completion files for bash that are in the `bash-completion` package that is installed by default on most distros (I guess).

that should teach me to test the debs after changing my script...
I'm sorry.

**Comment by Botspot** [comment]
> > Do you mean that anyone who now tries to install QEMU for the first time, it will be defective?
> 
> unfortunately yes, dpkg will fail because I accidentally copied completion files for bash that are in the `bash-completion` package that is installed by default on most distros (I guess).
> 
> that should teach me to test the debs after changing my script...
> I'm sorry.

We all make mistakes. Now we move on from the mistake and do our best to clean up and to minimize collateral damage.  

1. Can you revert your file hosting service to use your old, working deb?
2. Yes, testing stuff beforehand is an excellent preventative measure.

**Comment by Itai-Nelken** [comment]
> We all make mistakes. Now we move on from the mistake and do our best to clean up and to minimize collateral damage.
> 
> 1. Can you revert your file hosting service to use your old, working deb?
> 2. Yes, testing stuff beforehand is an excellent preventative measure.

from now on I'll be able to revert debs (because I won't delete the old one, just rename it), and I'll make sure to test each deb before uploading it.

**Pull request merged**
