### PR TITLE
Update tip for uploading files in app-request issue form

### PR DESCRIPTION
**Pull request by Itai-Nelken**
This isn't the best way to put it. but what I mean is that you can click on the text box to expand the regular github one and then you can upload files (not tested, but I see no reason for it not to work).

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
I also added a checkbox for making sure the app isn't piracy and is legal (@cycool29).

**Comment by cycool29** [comment]
I prefer transfer.sh because GitHub only supports `GIF, JPEG, JPG, MOV, MP4, PNG, CSV, DOCX, FODG, FODP, FODS, FODT, GZ, LOG, MD, ODF, ODG, ODP, ODS, ODT, PDF, PPTX, TXT, XLS, XLSX or ZIP`, some common used file types such as `XZ` and `DEB` is not included.



Maybe we should write :
```
Tips: You can upload files by here by clicking to expand the regular text-box.
      If the file type isn't supported, you can use transfer.sh and paste the link here.
```

**Comment by Itai-Nelken** [comment]
What do you prefer @Botspot?

**Comment by Botspot** [comment]
It's not optimal because Github refuses some filetypes, but this is an improvement so I'll merge it.

**Pull request merged**
