### PR TITLE
Added Stacer (32 bit)

### PR DESCRIPTION
**Pull request by open-sorcerer64**
Everything works. I cannot find RAM usage problems it's even with htop

### CODE REVIEW

**Comment by Botspot** [comment]
> I cannot find RAM usage problems it's even with htop

After fixing your broken scripts, I was able to test Stacer and the RAM-usage problem still persists.
2021-10-10-203100_1920x1080_scrot
My Raspberry Pi does not have 16777216 terabytes of RAM.

**Comment by open-sorcerer64** [comment]
Also, please fix the scripts in PR too

**Comment by cycool29** [comment]
Tested on my 32 bit RPi, the RAM-usage problem still persists.

image

**Comment by Botspot** [comment]
> hmmmm, now that's weird because I don't get that problem 

Well that's weird. Do you have a spare sd card to flash clean RPiOS to, to try Stacer on it?
Perhaps your system has a library installed that mine doesn't. If you could figure out this mystery, that would be great.

Sidenote: the measurement for my disk usage is completely wrong. My booted drive is 150GB and I'm using most of it. I'm not sure where Stacer is getting "`26.7 GiB / 29.0 GiB`" from.

**Comment by Botspot** [comment]
> > My Raspberry Pi does not have 16777216 terabytes of RAM.
> 
> It's because you're on 64-bit RPI OS it is meant only for 32-bit and it's clearly mentioned in the title.

Actually it is 32-bit. It's 32-bit Raspberry Pi OS, except that I enabled the 64-bit kernel. But it's still a 32-bit OS.
As @cycool29 demonstrated, this problem still occurs on systems with a 32-bit kernel.

**Comment by Itai-Nelken** [comment]
I'll try to see if I stacer actually gets the correct values but interprets them incorrectly or if it reads them incorrectly all along.

(what it does if I understood it correctly is read `/proc/meminfo` and uses a regular expression to get all the fields it needs and puts them in an array.
then it gets the string at a certain index in the array, splits it with spaces, gets the number (index 1, (arrays are 0-indexed), converts it to a long (8 byte integer), and [bitwise left-shifts](https://stackoverflow.com/questions/141525/what-are-bitwise-shift-bit-shift-operators-and-how-do-they-work) it by 10)

**Comment by open-sorcerer64** [comment]
Can anyone install Stacer from the terminal and see if the issue still persists?

```bash
sudo apt update
git clone https://github.com/open-sorcerer64/stacer-on-pi.git
cd ~/stacer-on-pi
sudo apt install libqt5charts5 -y
sudo dpkg -i fonts-inter.deb
sudo dpkg -i stacer.deb
```

**Comment by open-sorcerer64** [comment]
> > hmmmm, now that's weird because I don't get that problem
> 
> Well that's weird. Do you have a spare sd card to flash clean RPiOS to, to try Stacer on it? Perhaps your system has a library installed that mine doesn't. If you could figure out this mystery, that would be great.
> 
> Sidenote: the measurement for my disk usage is completely wrong. My booted drive is 150GB and I'm using most of it. I'm not sure where Stacer is getting "`26.7 GiB / 29.0 GiB`" from.
stacer

**Comment by cycool29** [comment]
> Can anyone install Stacer from the terminal and see if the issue still persists?
> 
> ```shell
> sudo apt update
> git clone https://github.com/open-sorcerer64/stacer-on-pi.git
> cd ~/stacer-on-pi
> sudo apt install libqt5charts5 -y
> sudo dpkg -i fonts-inter.deb
> sudo dpkg -i stacer.deb
> ```

Yes, it still show high RAM.

Also, I found latest version of `fonts-inter` and tested works. You may add it to your repo. @open-sorcerer64 
http://ftp.us.debian.org/debian/pool/main/f/fonts-inter/fonts-inter_3.19+ds-2_all.deb

**Comment by touhidurrr** [comment]
> https://user-images.githubusercontent.com/78641958/136969864-361b8dca-7bc5-4223-b3f3-228ee22f49bc.png

Off topic, but I am impressed by this desktop image. What distro are you using?

**Comment by open-sorcerer64** [comment]
> > https://user-images.githubusercontent.com/78641958/136969864-361b8dca-7bc5-4223-b3f3-228ee22f49bc.png
> 
> @open-sorcerer64 Off topic, but I am impressed by this desktop image. What distro are you using?

That's riced Raspberry Pi OS

**Comment by touhidurrr** [comment]
riced? how?

**Comment by open-sorcerer64** [comment]
2022-01-01-134148_1920x1080_scrot

I tested Stacer on 3 different installations. It seems Stacer works fine if there is an Ubuntu Repo present (i.e., it uses the repo somehow).

**Comment by touhidurrr** [comment]
> It seems Stacer works fine if there is an Ubuntu Repo present (i.e., it uses the repo somehow).

Lol, what does reporting Terabytes of RAM has anything to do with Ubuntu Repo. How made Stacer anyways?

**Comment by open-sorcerer64** [comment]
> > It seems Stacer works fine if there is an Ubuntu Repo present (i.e., it uses the repo somehow).
> 
> Lol, what does reporting Terabytes of RAM has anything to do with Ubuntu Repo. How made Stacer anyways?

To be honest, I don't know too but it atleast "IT WORKS!"

**Comment by touhidurrr** [comment]
This can also be Just the fault of @Botspot. Previously he reported Unciv not working when I was trying to add it. Later we found out that the problem was because of @Botspot running armhf Bin aries on ARM64 mode.

**Comment by touhidurrr** [comment]
Ok, sorry. I tested just now. The problem persists on my Pi. I will try to give the details asap.

**Comment by touhidurrr** [comment]
> > > It seems Stacer works fine if there is an Ubuntu Repo present (i.e., it uses the repo somehow).
> > 
> > 
> > Lol, what does reporting Terabytes of RAM has anything to do with Ubuntu Repo. How made Stacer anyways?
> 
> To be honest, I don't know too but it atleast "IT WORKS!"

It seems like stacer also installs `libqt5charts5`. so what if we install that from ubuntu repo?

**Comment by touhidurrr** [comment]
Ok, after testing stacer I came into the following conclusions.

1. Stacer is already in Raspbian repo and can be install direcctly from there.
2. The Raspbian repo stacer reports incorrect RAM also.
3. According to `open-sorcerer64` using Ubuntu repo solves that? It can be because `libqt5charts5` or some other dependencies that stacer has might have some bugfixes on Ubuntu repo. This fact is not tested.

**Conclusion:** Fact 3 needs to be tested and if it works we need to add some packages from ubuntu repo.

@open-sorcerer64 can you run `sudo apt purge --autoremove stacer libqt5charts5 fonts-inter` and then `sudo apt install stacer` and share us the installation logs of stacer? I don't want to install yet another repo.

**Comment by theofficialgman** [comment]
> This can also be Just the fault of @Botspot. Previously he reported Unciv not working when I was trying to add it. Later we found out that the problem was because of @Botspot running armhf Binaries on ARM64 mode.
> 
> Are you guys sure that's not the case here? Seems highly likely to me. Maybe something like some random bits added between the numbers because its being run on `arm64_bit` mode.

am64 kernel mode is an official supported mode by raspberry piOS, its not "botspots fault" no matter how much you want to say it is. There are a lot of areas where the 64bit kernel (even on a 32bit OS) is MUCH faster, so its the preferred version to use

**Comment by ryanfortner** [comment]
I just realized, there are two versions of stacer, [electron](https://github.com/oguzhaninan/Stacer/tree/electron) and [native](https://github.com/oguzhaninan/Stacer/tree/native). The Electron branch seems to be outdated but there's a possibility it could still build. I'll try to build it later.

**Comment by theofficialgman** [comment]
I think we should close this PR. Stacer is unmaintained (no commit for 6 months) and has 100s of unreplied issues and it doesn't seem to even run on the master branch

**Comment by Botspot** [comment]
Those are good reasons. Closing now.

**Pull request closed without merging**
