### PR TITLE
Add `snap` as dependency in Snap Store install script

### PR DESCRIPTION
**Pull request by cycool29**

### CODE REVIEW

**Comment by Botspot** [comment]
I don't think this is what you want.
According to `apt search`, the `snap` package is for DNA sequencing!
```
snap/oldstable 2013-11-29-9 armhf
  location of genes from DNA sequence with hidden markov model
```

**Comment by cycool29** [comment]
Ahh.. that's awkward. 🤣 This is recommended by @theofficialgman lol. 
Closing this PR first.

**Comment by Botspot** [comment]
> Ahh.. that's awkward. 🤣 This is recommended by @theofficialgman lol. Closing this PR first.

To be honest, I almost made the same change in response to the error logs. Glad I checked...! 🤣

**Comment by theofficialgman** [comment]
hmm... yes my bad
```
snap "core18" is already installed, see 'snap help refresh'
snap "core" is already installed, see 'snap help refresh'
error: cannot install "snapd": cannot install snapd snap on a model without a
       base snap yet
Snapd was unable to install snapd
```
so I guess what is this `"snapd": cannot install snapd snap on a model without a
       base snap yet` error then?

**Comment by theofficialgman** [comment]
All I find is people saying to purge snap (and in turn purging all installed snaps) and reinstalling
which is not a good solution

**Comment by cycool29** [comment]
I can only find https://forum.snapcraft.io/t/cannot-install-snapd-cannot-install-snapd-snap-on-a-model-without-a-base-snap-yet/10945 from Google... 
No much info on this error.

**Comment by Botspot** [comment]
Yeah I've researched this error several times and never got anywhere.

**Pull request closed without merging**
