### PR TITLE
Add Minecraft Pi

### PR DESCRIPTION
**Pull request by TheBrokenRail**
This adds the MCPI-Docker build of Minecraft Pi including a bunch of mods. I have not tested this yet, but it is relatively simple and should work. Because of the nature of some dependencies like Docker, this is unfortunately installed globally. However, it does run ``apt-get autoremove`` on uninstall.

MCPI-Docker Source: https://gitea.thebrokenrail.com/TheBrokenRail/minecraft-pi-docker

### CODE REVIEW

**Comment by Botspot** [comment]
Hey would you mind making me a zip for this? I've found that's a lot faster than a PR. (For testing, that is)

**Comment by TheBrokenRail** [comment]
Here you go: [Minecraft Pi.zip](https://github.com/Botspot/pi-apps/files/5699806/Minecraft.Pi.zip)

**Comment by Botspot** [comment]
Sorry for the delay, folks. Okay here's the first error:  
2020-12-17-163904_1920x1080_scrot

**Comment by TheBrokenRail** [comment]
Fixed! [Minecraft Pi.zip](https://github.com/Botspot/pi-apps/files/5712887/Minecraft.Pi.zip)

**Comment by Botspot** [comment]
Error output:
```
Installing Minecraft Pi with install script
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'docker.io' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 71 not upgraded.
# Executing docker install script, commit: 3d8fe77c2c46c5b7571f94b42793905e5b3e42e4
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
E: Sub-process /usr/bin/dpkg returned an error code (1)
Unable To Install Docker

Failed to install Minecraft Pi with install script!

Close this window to exit.
```

**Comment by zachdwilliams** [comment]
When do you think this will be released?

**Comment by Botspot** [comment]
> When do you think this will be released?

There are no guarantees TBH. It will have to work reliably before going to Pi-Apps. If you want to help the effort, I suppose you could test out @TheBrokenRail's releases before I get a chance.  
That would probably speed things up.

**Comment by TheBrokenRail** [comment]
> Error output:
> 
> ```
> Installing Minecraft Pi with install script
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package 'docker.io' is not installed, so not removed
> 0 upgraded, 0 newly installed, 0 to remove and 71 not upgraded.
> # Executing docker install script, commit: 3d8fe77c2c46c5b7571f94b42793905e5b3e42e4
> + sh -c apt-get update -qq >/dev/null
> + sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
> + sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
> Warning: apt-key output should not be parsed (stdout is not a terminal)
> + sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list
> + sh -c apt-get update -qq >/dev/null
> + [ -n  ]
> + sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> Unable To Install Docker
> 
> Failed to install Minecraft Pi with install script!
> 
> Close this window to exit.
> ```

What happens if you just run ``sudo apt-get install -y -qq --no-install-recommends docker-ce``? This seems to be where the error occurs.

**Comment by Botspot** [comment]
> What happens if you just run `sudo apt-get install -y -qq --no-install-recommends docker-ce`? This seems to be where the error occurs.

Good question. In the below output, I've removed `-qq`. This allows more output to reach the terminal. (`-qq` means "super-quiet")
```
pi@raspberrypi:~ $ sudo apt-get install -y --no-install-recommends docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
docker-ce is already the newest version (5:20.10.1~3-0~raspbian-buster).
0 upgraded, 0 newly installed, 0 to remove and 71 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up docker-ce (5:20.10.1~3-0~raspbian-buster) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-12-18 08:44:47 CST; 33ms ago
     Docs: https://docs.docker.com
  Process: 15804 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 15804 (code=exited, status=1/FAILURE)

Dec 18 08:44:47 raspberrypi systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 18 08:44:47 raspberrypi systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 18 08:44:47 raspberrypi systemd[1]: Failed to start Docker Application Container Engine.
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by zachdwilliams** [comment]
> There are no guarantees TBH. It will have to work reliably before going to Pi-Apps. If you want to help the effort, I suppose you could test out @TheBrokenRail's releases before I get a chance.

I’m actually getting my Pi on Christmas. I will check it out then.

**Comment by zachdwilliams** [comment]
What exactly are you guys having issues with?

**Comment by TheBrokenRail** [comment]
It looks like @Botspot's Raspberry Pi is having issues installing Docker for some reason.

**Comment by Botspot** [comment]
> It looks like @Botspot's Raspberry Pi is having issues installing Docker for some reason.

It's a brand new image running inside of [vdesktop](https://github.com/Botspot/vdesktop).

**Comment by zachdwilliams** [comment]
Ok

**Comment by TheBrokenRail** [comment]
Could vdesktop potentially be interfering with Docker since Docker does so much low-level stuff with the Linux Kernel?

**Comment by Botspot** [comment]
> Could vdesktop potentially be interfering with Docker since Docker does so much low-level stuff with the Linux Kernel?

It very well could be. But during installation? Maybe.

**Comment by Botspot** [comment]
Sorry about that. I accidentally merged the wrong PR.

**Comment by Botspot** [comment]
Is there a way to re-open this PR?

**Comment by Botspot** [comment]
> Is there a way to re-open this PR?

It doesn't look like it. Anyone who sees this PR, please reply to issue #144.

**Comment by Botspot** [comment]
@TheBrokenRail Please see #144.

**Pull request merged**
