### PR TITLE
Wait for apt lock to be released and add controls

### PR DESCRIPTION
**Pull request by mobilegmYT**

### CODE REVIEW

**Comment by mobilegmYT** [comment]
@Itai-Nelken

**Comment by Itai-Nelken** [comment]
Is it ready? If yes mark this pr as 'ready for review'

**Comment by mobilegmYT** [comment]
@Itai-Nelken

**Comment by Itai-Nelken** [comment]
Is this tested?

**Comment by mobilegmYT** [comment]
> Is this tested?

Yea, at worst it won't do anything.

**Comment by Itai-Nelken** [comment]
it seems that the wait for apt locks thing isn't working @mobilegmYT

**Comment by mobilegmYT** [comment]
> it seems that the wait for apt locks thing isn't working @mobilegmYT. it isn't doing anything.

Huh strange, I'll check it again

**Comment by mobilegmYT** [comment]
@Itai-Nelken I think you need to revert it and remerge it, this time I had the code checked by the devs from mcpi revival.

**Comment by Itai-Nelken** [comment]
@mobilegmYT what would reverting and remerging help? do you mean to revert and you will make a new pr?

**Comment by mobilegmYT** [comment]
> @mobilegmYT what would reverting and remerging help? do you mean to revert and you will make a new pr?

Oop, yea, revert and new PR.

**Pull request merged**
