### PR TITLE
Fix more dependencies on groovy in box86 arm64

### PR DESCRIPTION
**Pull request by Jai-JAP**
Fix more dependencies on groovy

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
I never had any problem not using those dependencies

**Comment by Botspot** [comment]
@Itai-Nelken I give you the choice whether or not to merge this.

**Comment by Itai-Nelken** [comment]
those extra dependencies aren't necessary to run box86, but it won't be bad to add them because more programs will run with box86. but they will also use more disk space that not everyone has.
I have to think a bit if its worth adding them.

**Comment by Itai-Nelken** [comment]
@Botspot what do you think is beter:
1) installing a bit more dependencies but more things work "out-of-the-box"
2) installing less dependencies to save disk space.

personally I prefer the first option (which means I decided its a good idea to merge this pr) but I want to know what do you think.
I also want your opinions @mobilegmYT and @CleanMachine1 .

**Comment by CleanMachine1** [comment]
2 

Install when needed not before

But i have no context about what this regards.

**Comment by Itai-Nelken** [comment]
> But i have no context about what this regards.

if some extra dependencies for box86 on arm64 should be added or not.
thanks for your opinion

**Comment by Itai-Nelken** [comment]
> But i have no context about what this regards.

if some extra dependencies for box86 on arm64 should be added or not.
thanks for your opinion

**Comment by CleanMachine1** [comment]
@Itai-Nelken What is the total size of the new dependencies?

**Comment by Itai-Nelken** [comment]
> @Itai-Nelken What is the total size of the new dependencies?

@CleanMachine1 I don't know, can you check?
here are the extra dependencies: `libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf libc6:armhf`

**Comment by CleanMachine1** [comment]
Give me a few mins and I'll check but I don't use Ubuntu on a pi
so I may not see some

**Comment by CleanMachine1** [comment]
On a raspberry pi Lite server install, it come with most however what it does install, its 5.188kb

**Comment by Itai-Nelken** [comment]
@CleanMachine1 I accidentally put the wrong dependencies, those are the correct extra ones:
```
libraspberrypi0:armhf  libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf  libssl1.1:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf
```
sorry

**Comment by Itai-Nelken** [comment]
> On a raspberry pi Lite server install, it come with most however what it does install, its 5.188kb

so its worth installing the extra dependencies.

**Comment by Itai-Nelken** [comment]
@Botspot I say merge

**Comment by CleanMachine1** [comment]
yeah but all of these were already installed 

```
libc6 is already the newest version (2.28-10+rpi1).
libcups2 is already the newest version (2.2.10-6+deb10u4).
libcups2 set to manually installed.
libgssapi-krb5-2 is already the newest version (1.17-3+deb10u1).
libgssapi-krb5-2 set to manually installed.
libkrb5-3 is already the newest version (1.17-3+deb10u1).
libkrb5-3 set to manually installed.
libraspberrypi0 is already the newest version (1.20210303-1).
libssl1.1 is already the newest version (1.1.1d-0+deb10u6+rpt1).
```

**Comment by CleanMachine1** [comment]
Ignore me 

```
$ sudo apt show libraspberrypi0 libssh-gcrypt-4 libgssapi-krb5-2 libkrb5-3 libssl1.1 libcups2 libsdl1.2debian libopusfile0 libc6 | grep Size

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Installed-Size: 3,251 kB
Download-Size: 847 kB
Installed-Size: 516 kB
Download-Size: 171 kB
Installed-Size: 367 kB
Download-Size: 135 kB
Installed-Size: 938 kB
Download-Size: 320 kB
Installed-Size: 3,090 kB
Download-Size: 1,277 kB
Installed-Size: 623 kB
Download-Size: 287 kB
Installed-Size: 470 kB
Download-Size: 168 kB
Installed-Size: 91.1 kB
Download-Size: 33.5 kB
Installed-Size: 9,198 kB
Download-Size: 2,355 kB
```

**Comment by CleanMachine1** [comment]
Merge

**Comment by Itai-Nelken** [comment]
@Botspot this is ready to merge.

**Comment by Botspot** [comment]
ok

**Pull request merged**
