### PR TITLE
fix 'nvm: command not found'

### PR DESCRIPTION
**Pull request by scamdotnet**

### CODE REVIEW

**Comment by Botspot** [comment]
I was having the same problem this morning. Thank you! :)

**Comment by scamdotnet** [comment]
NP

**Comment by Botspot** [comment]
> NP

Any ideas?
```
pi@raspberrypi:~/edex-ui $ npm run install-linux
/usr/bin/env: 'node': No such file or directory
pi@raspberrypi:~/edex-ui $ [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
Please see `nvm --help` or https://github.com/nvm-sh/nvm#nvmrc for more information.
pi@raspberrypi:~/edex-ui $ [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
pi@raspberrypi:~/edex-ui $ npm run install-linux
/usr/bin/env: 'node': No such file or directory
pi@raspberrypi:~/edex-ui $ nvm install --lts
Installing latest LTS version.
v14.16.0 is already installed.
Now using node v14.16.0 (npm v)
pi@raspberrypi:~/edex-ui $ npm run install-linux
/usr/bin/env: 'node': No such file or directory
pi@raspberrypi:~/edex-ui $ 
```

**Comment by scamdotnet** [comment]
> > NP
> 
> @scamdotnet
> Any ideas?
> 
> ```
> pi@raspberrypi:~/edex-ui $ npm run install-linux
> /usr/bin/env: 'node': No such file or directory
> pi@raspberrypi:~/edex-ui $ [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
> Please see `nvm --help` or https://github.com/nvm-sh/nvm#nvmrc for more information.
> pi@raspberrypi:~/edex-ui $ [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
> pi@raspberrypi:~/edex-ui $ npm run install-linux
> /usr/bin/env: 'node': No such file or directory
> pi@raspberrypi:~/edex-ui $ nvm install --lts
> Installing latest LTS version.
> v14.16.0 is already installed.
> Now using node v14.16.0 (npm v)
> pi@raspberrypi:~/edex-ui $ npm run install-linux
> /usr/bin/env: 'node': No such file or directory
> pi@raspberrypi:~/edex-ui $ 
> ```

Hmm, no ideas, honestly I have no clue what I'm doing xD. I'm just trying to fix things I know how to fix.

**Pull request merged**
