### PR TITLE
Fix typo in `pkg-install` script

### PR DESCRIPTION
**Pull request by cycool29**
Fix `pkg-install: failed to mark the  package as autoremovable.` in few error reports.

### CODE REVIEW

**Comment by cycool29** [comment]
@Botspot This typo is quite serious since almost all error reports received failed at `pkg-install: failed to mark the package as autoremovable.`

**Comment by cycool29** [comment]
@Botspot

**Comment by Botspot** [comment]
> @Botspot This typo is quite serious since almost all error reports received failed at `pkg-install: failed to mark the package as autoremovable.`

I know. I'm sorry, I was asleep. It's been fixed in commit https://github.com/Botspot/pi-apps/commit/ca767e248814e30b52e1f8e4c1dd0551d372a365.

**Comment by cycool29** [comment]
> > @Botspot This typo is quite serious since almost all error reports received failed at `pkg-install: failed to mark the package as autoremovable.`
> 
> I know. I'm sorry, I was asleep. It's been fixed in commit [ca767e2](https://github.com/Botspot/pi-apps/commit/ca767e248814e30b52e1f8e4c1dd0551d372a365).

Lol just tagging so once you awake you can see it.

**Pull request closed without merging**
