### PR TITLE
Get MCPI Modded to update.

### PR DESCRIPTION
**Pull request by RaspberryPiNews**
This is just a useless variable that makes pi-apps reinstall it and update to the latest version with a reinstall.

NOTE: The latest version didn't start for me, so wait until I say so before mergining

### CODE REVIEW

**Comment by Botspot** [comment]
You know we could just add a space character in somewhere to force an update. ;)

So, if every new version of Minecraft Pi has changed `MCPIL_VERSION`, wouldn't that mean that everybody is currently running 0.1.8?

**Comment by RaspberryPiNews** [comment]
> So, if every new version of Minecraft Pi has changed `MCPIL_VERSION`, wouldn't that mean that everybody is currently running 0.1.8?

Well there's MCPI-Reborn and MCPIl, which are 2 seprate programs.

**Comment by Botspot** [comment]
> > So, if every new version of Minecraft Pi has changed `MCPIL_VERSION`, wouldn't that mean that everybody is currently running 0.1.8?
> 
> Well there's MCPI-Reborn and MCPIl, which are 2 seprate programs.

Isn't one of those an apt package that would stay updated with an `apt upgrade`?

**Comment by RaspberryPiNews** [comment]
> > > So, if every new version of Minecraft Pi has changed `MCPIL_VERSION`, wouldn't that mean that everybody is currently running 0.1.8?
> > 
> > 
> > Well there's MCPI-Reborn and MCPIl, which are 2 seprate programs.
> 
> Isn't one of those an apt package that would stay updated with an `apt upgrade`?

None of them are in a apt repo.

**Comment by Botspot** [comment]
Okay I'll merge this then.

**Comment by RaspberryPiNews** [comment]
@Botspot I DIDNT SAY TO MERGE IT!!!! THE LATEST VERSION IS BROKEN!!!!!!!!

**Comment by Botspot** [comment]
Sigh...

Okay I undid it to minimize the damage done. This is why update checking is set to daily by default - for situations exactly like this.

**Comment by Botspot** [comment]
Okay I updated and you're right - it doesn't work.

`[ERR]: Invalid ~/.minecraft-pi Permissions`

That sounds like an easy fix...

**Comment by RaspberryPiNews** [comment]
> Okay I updated and you're right - it doesn't work.
> 
> `[ERR]: Invalid ~/.minecraft-pi Permissions`
> 
> That sounds like an easy fix...

Thats a small issue with updating. The big issue is that he broke the glsw stuff and now the game doesnt launch

**Comment by mobilegmYT** [comment]
> You know we could just add a space character in somewhere to force an update. ;)

It's also good for debugging purposes to see what version they are using 😉

**Pull request merged**
