### PR TITLE
remove all parts from the readme that are in the wiki

### PR DESCRIPTION
**Pull request by Itai-Nelken**
almost all parts

### CODE REVIEW

**Comment by Botspot** [comment]
I'd like to leave the basic usage intact. It's something 100% of users will want to know.

**Comment by Itai-Nelken** [comment]
> I'd like to leave the basic usage intact. It's something 100% of users will want to know.

I'm just doing that

**Comment by Itai-Nelken** [comment]
@Botspot it appears anybody can edit the wiki page without cofirmation! maybe lock it down a bit?

**Comment by Botspot** [comment]
> @Botspot it appears anybody can edit the wiki page without cofirmation! maybe lock it down a bit?

Uhh, how would I do that?

**Comment by Itai-Nelken** [comment]
> > @Botspot it appears anybody can edit the wiki page without cofirmation! maybe lock it down a bit?
> 
> Uhh, how would I do that?

I don't know, check the settings.

**Pull request merged**
