### PR TITLE
Updated new link and added alias for AIW

### PR DESCRIPTION
**Pull request by spectrumgamer75**
This update for AIW adds the new download link for the script along with adding an alias for launching directly from the terminal.

### CODE REVIEW

**Comment by Botspot** [comment]
Make sure the uninstall script reverts all changes, including the alias.

**Comment by spectrumgamer75** [comment]
That is being worked on, will add that soon in the uninstall script too.

**Comment by Botspot** [comment]
OK. Then I can wait.

**Comment by spectrumgamer75** [comment]
Have added that now.

**Pull request merged**
