### PR TITLE
Add discord support link to MCPI app's description

### PR DESCRIPTION
**Pull request by nobody5050**

### CODE REVIEW

**Comment by CleanMachine1** [comment]
Why would the MCPi revival discord be support, support is more for the pi-apps discord I would assume and here in the issues section

**Comment by mobilegmYT** [comment]
> Why would the MCPi revival discord be support, support is more for the pi-apps discord I would assume and here in the issues section

Dude read the commit, its for description in mcpi modded app.

**Comment by CleanMachine1** [comment]
:laughing: I am stupid I thought there was a support link for downloading discord.

**Comment by Botspot** [comment]
> Dude read the commit, its for description in mcpi modded app.

I immediately thought the same thing by looking at the issue title. Only after clicking "Files changed" did I realize the truth.
@mobilegmYT Please remember that @CleanMachine1's mistake was very easy to make, Botspot made the same mistake, it's not a big deal, and it's certainly not anything to say "dude read the commit" about.

**Comment by Botspot** [comment]
Title has been changed from "Add support discord to description" to "Add discord support link to MCPI app's description".

**Comment by mobilegmYT** [comment]
> > Dude read the commit, its for description in mcpi modded app.
> 
> I immediately thought the same thing by looking at the issue title. Only after clicking "Files changed" did I realize the truth.
> @mobilegmYT Please remember that @CleanMachine1's mistake was very easy to make, Botspot made the same mistake, it's not a big deal, and it's certainly not anything to say "dude read the commit" about.

Sorry, I didn't intend to convey and anger or frustation.

**Comment by CleanMachine1** [comment]
I didn't take any offence to my own stupidity :rofl: 
I think it justs sounds a little rude but I don't care really

**Comment by nobody5050** [comment]
Sorry about the inadequate commit message, I didn’t realize this could lead to confusion

**Pull request merged**
