### PR TITLE
Close programs before uninstalling

### PR DESCRIPTION
**Pull request by Rak1ta**
Close programs that may be running in the background before uninstalling.

### CODE REVIEW

**Comment by Botspot** [comment]
@Rak1ta, Do you plan to add other apps to this PR so it becomes the new default Pi-Apps behavior? Or are you opnly planning on making this change to these two apps?

**Comment by Rak1ta** [comment]
@Botspot If necessary, I can add other programs to this PR.

**Comment by Botspot** [comment]
> @Botspot If necessary (i wanted to add only those that can run in the background) , I can add other programs to this PR.

I can merge this now if you want me to. Just let me know.

**Comment by Rak1ta** [comment]
@Botspot If possible (if these changes are needed), merge this request, but **without AnyDesk** (it closes automatically when uninstalled). Added something that I did not close automatically (from the list of what I have installed).
I have this for you as an idea. If the user removes the program, but it works, ask for confirmation. For example, a torrent client or browser that can download. But it's probably a waste of time.

**Pull request merged**
