### PR TITLE
Add GeyserMC

### LINKED ISSUE #2381: GeyserMC install script
### What is the name of the app?

Geyser

### (Optional) Where is the app hosted?

https://geysermc.org
https://github.com/geysermc/geyser

### About the app

Geyser is a modified Minecraft Bedrock Dedicated Server that allows Bedrock-based clients to join Minecraft (java edition) servers.

### Upload file or Add PR Link

#2380 

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

### PR DESCRIPTION
**Pull request by libewa**
fixes #2381

### CODE REVIEW

**Comment by theofficialgman** [comment]
as I understand it this is the standalone install of GeyserMC (not the plugin/mod version for spigot/paper/etc servers).

What is your intention with the standalone versions? Is it so that you can connect from the bedrock version of minecraft to any arbitrary java edition server or is it to connect to a java edition server that you run? If it is the latter, I think the mod/plugin version would be more appropriate to integrate into the [Minecraft Java Server](https://github.com/Botspot/pi-apps/tree/master/apps/Minecraft%20Java%20Server) app

**Comment by libewa** [comment]
its the first.

**Comment by theofficialgman** [comment]
> its the first.

I think you should update the description to state that as well as the minimum java server version of 1.20.
Maybe this other info as well

> The server you are connecting to has to support the latest version of Minecraft: Java Edition (at this time this is Minecraft 1.20/1.20.1) The server itself does not have to be the latest version but does have to allow connections. If you’re running the server on an older version, you can use the plugin [ViaVersion](https://www.spigotmc.org/resources/19254/).

> The device running Geyser must support Java 16 or later. If you need help installing or updating, please see [PaperMC’s Java update page](https://paper.readthedocs.io/en/latest/java-update/index.html).

> If you are connecting to an online mode Java server, a paid Java account is required. If you are running the server, you can bypass this requirement for your server with [Floodgate](https://wiki.geysermc.org/floodgate/).

> Your Bedrock client has to be a supported version - at this time that is Bedrock version(s) 1.19.80-1.20.1.

> To allow Geyser Standalone to be reached outside the local network, Unlike Minecraft: Java Edition, Bedrock Edition runs on port 19132 on the UDP protocol. When port forwarding, make sure to allocate to 19132 UDP or another UDP port.

> Currently, Geyser does not support key signing. To disable it (on servers running version 1.19 and higher), follow these instructions: Spigot, Paper, & all forks: Set enfore-secure-profile: false in the server.properties file. On BungeeCord: Set enforce_secure_profile: false in your config.yml. Using Velocity: set force-key-authentication = false in your velocity.toml.

**Comment by theofficialgman** [comment]
closing as stale. changes were requested but not made.

I also do not have the ability nor desire to maintain or provide support for this application and another pi-apps maintainer would need to do so.

**Pull request closed without merging**
