### PR TITLE
Add ReaPack (Reaper Package Manager)

### PR DESCRIPTION
**Pull request by Crilum**
This is a Reaper package manager, which is home to over 1300 Reaper plugins and addons (synths, Web Interfaces, APIs, themes, and more).

Website: https://reapack.com
GH Repo: https://github.com/cfillion/reapack

This PR changes: new update script, added ReaPack to categories, added ReaPack app.

### CODE REVIEW

**Comment by Botspot** [comment]
Only Reaper users will be interested in this. Nobody would want ReaPack without first installing Reaper. (Right?)
Thus, I suggest changing the Reaper app's scripts to include ReaPack, either optionally, or by default.

**Comment by theofficialgman** [comment]
I agree with botspot, this is literally just an extra binary (which is funny, I've never seen anyone just drop `.so` files as a github release)
```
wget "https://github.com/cfillion/reapack/releases/download/v${version}/reaper_reapack-armv7l.so" || error "Failed to download ReaPack!!!"
```
I suggest just adding this to the the Reaper install script. you can put it behind a user input prompt if you want to make it optional, but honestly I don't see an issue with including it by default

**Comment by Crilum** [comment]
> (which is funny, I've never seen anyone just drop .so files as a github release)

ReaPack opens inside of Reaper, so I guess Reaper uses .so files? :man_shrugging:

**Comment by Crilum** [comment]
Okay... I'll close this PR and open another one to add Reapack to Reaper.

**Pull request closed without merging**
