### PR TITLE
update eDEX-UI to 2.2.7

### PR DESCRIPTION
**Pull request by Itai-Nelken**
there are official armv7l releases now: https://github.com/GitSquared/edex-ui/releases/latest

### CODE REVIEW

**Comment by Botspot** [comment]
There were several issues in your script. Good thing I caught them!

Next, when I try to run eDEX-UI 2.2.6 in the terminal, it does not load. Error output:
```bash
pi@raspberrypi:~ $ sudo modprobe fuse; $HOME/eDEX-UI-RPi/eDEX-UI-Linux-armv7l_2.2.6.AppImage
▶  start     Starting eDEX-UI v2.2.6
ℹ  info      With Node 12.18.3 and Electron 11.3.0
ℹ  info      Renderer is Chrome 87.0.4280.141
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/pi/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_eDEX-Uqnu5Ae/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_eDEX-Uqnu5Ae/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_eDEX-Uqnu5Ae/resources/app.asar/classes/terminal.class.js
- /tmp/.mount_eDEX-Uqnu5Ae/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-Uqnu5Ae/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:31:15)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_eDEX-Uqnu5Ae/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_eDEX-Uqnu5Ae/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_eDEX-Uqnu5Ae/resources/app.asar/classes/terminal.class.js',
    '/tmp/.mount_eDEX-Uqnu5Ae/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:14470) UnhandledPromiseRejectionWarning: Error: /tmp/.org.chromium.Chromium.DDygeZ: wrong ELF class: ELFCLASS64
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-Uqnu5Ae/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
(node:14470) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14470) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Botspot** [comment]
> is the issue with my script or with the appimage?

There were issues with your script. I had to fix those issues. Then the appimage failed to run.

Could you try running the appimage on your system?

**Comment by Itai-Nelken** [comment]
yes, what where the issues with my script?

**Comment by Itai-Nelken** [comment]
I have the same problem as you, I'll open a issue in its repo.

**Comment by Itai-Nelken** [comment]
https://github.com/GitSquared/edex-ui/issues/1051#issue-813594187

**Comment by Botspot** [comment]
> yes, what where the issues with my script?

A syntax error in one of the URLs due to the parenthesis. Fixed by putting it in quotes.

Also you referenced a nonexistent folder structure.

Good:  
`wget https://github.com/GitSquared/edex-ui/releases/download/v2.2.6/eDEX-UI-Linux-armv7l.AppImage -O ~/eDEX-UI-RPi/eDEX-UI-Linux-armv7l_2.2.6.AppImage'`  
Bad:  
`wget https://github.com/Botspot/eDEX-UI-RPi/raw/main/eDEX-UI%20Linux%20(armv7l)_3.0.0.AppImage -O ~/`**`eDEX-UI-RPi/'eDEX-UI-RPi`**`/eDEX-UI-Linux-armv7l_3.0.0.AppImage'`
`chmod +x ./'`**`eDEX-UI-RPi/eDEX-UI-RPi`**`/eDEX-UI-Linux-armv7l_2.2.6.AppImage' ./'eDEX-UI-RPi/eDEX-UI-Linux-armv7l_3.0.0.AppImage'`

I've fixed those issues for you just now.

**Comment by Itai-Nelken** [comment]
oops, thanks for fixing them!

**Comment by Itai-Nelken** [comment]
https://github.com/GitSquared/edex-ui/issues/1051#issuecomment-783580708
should work now thanks to you @Botspot.

**Comment by mobilegmYT** [comment]
@Botspot ^

**Comment by Botspot** [comment]
> @Botspot ^

As far as I know, it still doesn't work. That is, @GitSquared hasn't fixed his automated build pipeline for ARM devices.

**Comment by Itai-Nelken** [comment]
we cam still add the appimage that works though.

**Comment by Itai-Nelken** [comment]
@Botspot you beat me to change the title :)

**Comment by Botspot** [comment]
Novaspirit's 3.0.0 takes forever to load, but @gitsquared's appimage loads nearly instantly.

Because of that, I think it may make the most sense to only distribute the fast-loading appimage, and to ditch 3.0.0.

**Comment by Itai-Nelken** [comment]
I removed 3.0.0

**Comment by Botspot** [comment]
` || error 'Failed to mark the appimage's as executable!'`
That caused this error:
```
/home/pi/pi-apps/apps/eDEX-UI/install-32: line 13: unexpected EOF while looking for matching `''
/home/pi/pi-apps/apps/eDEX-UI/install-32: line 28: syntax error: unexpected end of file
```
I'll fix it offline.

**Comment by Itai-Nelken** [comment]
added by @Botspot in commit d15498cb7a3bfe9e75f2c0636fdf9a54a557e6d5.

**Pull request closed without merging**
