### PR TITLE
Update whatsapp links (changed its repo name) + fixed typo in createapp

### PR DESCRIPTION
**Pull request by Itai-Nelken**

### CODE REVIEW

**Comment by Botspot** [comment]
I thought we agreed to leave Etcher as-is.

**Comment by Itai-Nelken** [comment]
> I thought we agreed to leave Etcher as-is.

this has nothing to do with etcher, I fixed a typo I found in the `createapp` script and changed the link of the whatsapp web download because I renamed its repo.

**Comment by Itai-Nelken** [comment]
nvm, I used the same fork thast why the etcher commits are there.

**Comment by Itai-Nelken** [comment]
I'll fork again and open a new pr.

**Pull request closed without merging**
