### PR TITLE
Use debs to install AntiMicroX

### PR DESCRIPTION
**Pull request by cycool29**
To avoid compile errors when installation, as seen in error reports.
﻿

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
https://github.com/Pi-Apps-Coders/files/pull/9 ghas been merged.

**Comment by cycool29** [comment]
@Botspot

**Comment by Crilum** [comment]
There is a new release, 3.2.1, so we should update the deb.

However, with @theofficialgman's auto-update PR, when that gets merged, we could have a script that compiles AntiMicroX, builds a deb, and uploads it to a repository (maybe Pi-Apps-Coders/files).

**Comment by Crilum** [comment]
I'm working on a GitHub actions deb builder script for AntiMicroX ([here](https://github.com/Crilum/Github-Actions-App-Builds)), but since GitHub doesn't have arm runners, I can't do a fully automatic script, unless I have my Pi on all the time...

I did try using QEMU, but I couldn't get it to work.

**Comment by Crilum** [comment]
This is my current deb:  [antimicrox_3.2.1_armhf.deb.zip](https://github.com/Botspot/pi-apps/files/7850212/antimicrox_3.2.1_armhf.deb.zip) (Don't update Pi-Apps to use this)
Or it  can be found [here](https://pipelines.actions.githubusercontent.com/VdrZASlTnS6PKBp4tdDPzsjq2csvjdMA9fHg506Oq7NielHY9x/_apis/pipelines/1/runs/28/signedartifactscontent?artifactName=antimicrox_3.2.1_armhf.deb&urlExpires=2022-01-11T21%3A42%3A41.2491613Z&urlSigningMethod=HMACV2&urlSignature=VTGjqIRDgk%2FNJl0jVNWmkOIMAlwRILJ7Wwp0jbd1yZY%3D)
@cycool29 where did you get all the stuff in your deb? Mine works, but I don't have any icons, or .desktop files, or man pages, just the executable..

**Pull request merged**
