### PR TITLE
Add support for Minecraft Java v1.17

### PR DESCRIPTION
**Pull request by chunky-milk**

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
Is this tested?

**Comment by chunky-milk** [comment]
> Is this tested? 

I tested it on 32bit Raspberry Pi OS and it works. I will test 64bit later

**Comment by chunky-milk** [comment]
@Itai-Nelken I fixed the jvm arguments so the game actually launches now. I tested it on 64 and 32 bit, both work.

**Comment by Itai-Nelken** [comment]
Ok, I will merge later

**Comment by mobilegmYT** [comment]
@Itai-Nelken ?

**Comment by Itai-Nelken** [comment]
Sorry, I forgot.

**Pull request merged**
