### PR TITLE
Added Descent 1 and 2 games (dxx-rebirth port)

### PR DESCRIPTION
**Pull request by dimag0g**
Hi Botspot,

Here's my installation script for an RPi build of Descent 1 and 2 games, based on dxx-rebirth engine.
The scripts downloads shareware versions of the games on installation, while trying to preserve the game data provided by the user, if there is any.

Those games exist as Debian packages (https://packages.debian.org/stable/d1x-rebirth), but are hopelessly broken on the Pi, segfaulting soon after the rendering starts.

I tried to make sure the necessary dependencies (as listed on the Debian package page) are installed, but to be honest I didn't test the installation on a vanilla image.

### CODE REVIEW

**Comment by mobilegmYT** [comment]
@Botspot ?

**Comment by Botspot** [comment]
@dimag0g Could you please turn those into zips for easier testing and collaboration?

**Comment by dimag0g** [comment]
@Botspot, what do you mean? Should I put executables into zips?

**Comment by mobilegmYT** [comment]
> @Botspot, what do you mean? Should I put executables into zips?

He meant to grab all the files in the commit and put them in a zip

**Comment by Itai-Nelken** [comment]
> @Botspot, what do you mean? Should I put executables into zips?

no, he means take the folder containing the scripts, website, description, and credits file and the icons and zip it.
the folder will be in `$HOME/pi-apps/apps/`

**Comment by Botspot** [comment]
> > @Botspot, what do you mean? Should I put executables into zips?
> 
> no, he means take the folder containing the scripts, website, description, and credits file and the icons and zip it.
> the folder will be in `$HOME/pi-apps/apps/`

Yes, preferably each app folder in its own zip file.

So in your case, you'd send me d1x-rebirth.zip and d2x-rebirth.zip, each containing the app's respective files and icons.

**Comment by dimag0g** [comment]
@Botspot Here you are!
[d1x-rebirth.zip](https://github.com/Botspot/pi-apps/files/6111047/d1x-rebirth.zip)
[d2x-rebirth.zip](https://github.com/Botspot/pi-apps/files/6111049/d2x-rebirth.zip)

**Comment by Botspot** [comment]
Hmm...
```
pi@raspberrypi:~ $ shellcheck /home/pi/pi-apps/apps/d1x-rebirth/install-32

In /home/pi/pi-apps/apps/d1x-rebirth/install-32 line 1:
#!/bin/bash
           ^-- SC1017: Literal carriage return. Run script through tr -d '\r' .


In /home/pi/pi-apps/apps/d1x-rebirth/install-32 line 2:
function error {
                ^-- SC1017: Literal carriage return. Run script through tr -d '\r' .
```

**Comment by Botspot** [comment]
After fixing the line endings, it installs fine.

One correction: [don't use apt, use pkg-install.](https://github.com/Botspot/pi-apps#other-things-to-be-aware-of)

The game launched fine, but I couldn't figure out how to close it! (window-border X button did nothing)  
Finally I had to run `xkill` to terminate the window. Consider mentioning in the description how to close the game.

Also, the first line of the description should be a **short explanation** of what the app is. Something like, "Free version of action shooter game", or something about that length.  
The first line of the description is the hover-text, aka "tooltip". It's the text that appears when users hover over it in the list of apps.

**Comment by dimag0g** [comment]
@Botspot Sorry, I forgot that windows git does all kinds of molesting to text files. Here are zips created directly on the Pi.
[d1x-rebirth.zip](https://github.com/Botspot/pi-apps/files/6111381/d1x-rebirth.zip)
[d2x-rebirth.zip](https://github.com/Botspot/pi-apps/files/6111382/d2x-rebirth.zip)

**Comment by dimag0g** [comment]
@Botspot 
Sorry, I forgot how windows git is molesting text files. Made the new zips directly on the Pi.
Install scripts are using `pgk-install` now.

The game closes if you pick "quit" in the menu. I assumed this was obvious, now it's in the description. I will check why the game can't be closed by the window manager.

The description is now multi-line, with the first line taken directly from the official [.desktop files](https://github.com/dxx-rebirth/dxx-rebirth/blob/master/d1x-rebirth/d1x-rebirth.desktop)
[d2x-rebirth.zip](https://github.com/Botspot/pi-apps/files/6111559/d2x-rebirth.zip)
[d1x-rebirth.zip](https://github.com/Botspot/pi-apps/files/6111560/d1x-rebirth.zip)

**Comment by dimag0g** [comment]
@Botspot. No problem. I believe "Descent 1" / "Descent 2" are the names the end user cares about. Do you need new zip files, new git commit, or both?

**Comment by Botspot** [comment]
> @Botspot. No problem. I believe "Descent 1" / "Descent 2" are the names the end user cares about. Do you need new zip files, new git commit, or both?

Neither.  
I can rename the folders locally and then push them via git.

**Comment by dimag0g** [comment]
OK, cool. Don't forget to change the name in the pkg-install line.

**Comment by Botspot** [comment]
Done. I made many improvements to the scripts, namely changing the icon=line in the desktop launcher to be flexible based on Pi-Apps's installation location, and fixed your `pkg-install` and `purge-installed` implementation.

**Pull request closed without merging**
