### PR TITLE
Add Caprine

### PR DESCRIPTION
**Pull request by cycool29**
Caprine is an unofficial and privacy-focused Facebook Messenger app with many useful features. Built with Electron, Caprine features a Dark mode, keyboard shortcuts, the ability to toggle last seen/typing indicators, work chat support, code blocks, custom text size, and an interface that adapts to resizing windows.

https://github.com/sindresorhus/caprine
https://github.com/mquevill/caprine﻿

### CODE REVIEW

**Comment by Crilum** [comment]
armhf works for me, I don't have Facebook so I cant do anything but launch it, but that works great!

**Comment by Botspot** [comment]
Works great for me too. Its RAM footprint is much lower than running Facebook in a browser, so that's a bonus.

@cycool29, out of curiosity, why is this deb being downloaded from [pi-apps-coders](https://github.com/Pi-Apps-Coders/files)? If it's available somewhere else more official, I'd prefer using that to indicate that we don't "own", or take responsibility for, the deb.

**Comment by Botspot** [comment]
Oh I just noticed that the uninstall script is missing.

**Comment by Crilum** [comment]
Well, they're just debs...

**Comment by cycool29** [comment]
> @cycool29, out of curiosity, why is this deb being downloaded from [pi-apps-coders](https://github.com/Pi-Apps-Coders/files)? If it's available somewhere else more official, I'd prefer using that to indicate that we don't "own", or take responsibility for, the deb.

That's because the one from https://github.com/mquevill/caprine is a little bit outdated (the owner seems not to update it regularly), so I compiled the deb myself.

> Oh I just noticed that the uninstall script is missing.

Ahh, maybe I missed it when uploading the files. I will add that now.

**Comment by cycool29** [comment]
> > @cycool29, out of curiosity, why is this deb being downloaded from [pi-apps-coders](https://github.com/Pi-Apps-Coders/files)? If it's available somewhere else more official, I'd prefer using that to indicate that we don't "own", or take responsibility for, the deb.
> 
> That's because the one from https://github.com/mquevill/caprine is a little bit outdated (the owner seems not to update it regularly), so I compiled the deb myself.
> 
> > Oh I just noticed that the uninstall script is missing.
> 
> Ahh, maybe I missed it when uploading the files. I will add that now. It should be just `purge_packages | exit 1`.

**Pull request merged**
