### PR TITLE
Fix some WhatsApp issue

### PR DESCRIPTION
**Pull request by cycool29**
- Built with latest nativefier to solve `Old build detected` warning.

- Fix `To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.` by deleting service worker every time when WhatsApp launch. I know there are several JS injection solution on the web but they are often not working. 

**NOTE**: The service worker fix tested works perfectly in **normal version WhatsApp** but in **Multi-device beta** it will show a prompt like this:

update_available

Still exploring for fix of this bug...

### CODE REVIEW

**Comment by Botspot** [comment]
Thank you for seeing a problem and taking the time to solve it. We need more people like you.

Your scripts had a few problems (like not marking run-whatsapp as executable, not formatting the desktop file correctly, and not removing the right filenames during an uninstall)
I've modified the scripts so that they do work correctly, but am unable to fully test them because I don't have a WhatsApp account. Could you try it?
[WhatsApp.zip](https://github.com/Botspot/pi-apps/files/7211313/WhatsApp.zip)
Simply extract that zip file to your pi-apps/apps folder.

**Comment by Botspot** [comment]
Also tagging @Itai-Nelken - he might be interested in testing the zip before it goes live.

**Comment by cycool29** [comment]
> Thank you for seeing a problem and taking the time to solve it. We need more people like you.
> 
> Your scripts had a few problems (like not marking run-whatsapp as executable, not formatting the desktop file correctly, and not removing the right filenames during an uninstall)
> I've modified the scripts so that they do work correctly, but am unable to fully test them because I don't have a WhatsApp account. Could you try it?
> [WhatsApp.zip](https://github.com/Botspot/pi-apps/files/7211313/WhatsApp.zip)
> Simply extract that zip file to your pi-apps/apps folder.

Thanks for improving my script. I tested it locally and ran with pi-apps, it installed and launched perfectly.
The only problem is the uninstalling script as I changed the app name to `WhatsApp` instead of `WhatsAppWeb`. I made some commits adding the updated script and update uninstalling script. 😁

**Comment by Botspot** [comment]
Tested again by me and it works fine. In the absence of @Itai-Nelken, I'm merging the PR without his test-results, but that's not a big deal.

**Comment by Itai-Nelken** [comment]
I haven't tested it, but it looks good to me (not that it matters anymore).

**Comment by Itai-Nelken** [comment]
@cycool29 the following JS injection code works fine for deleting the service worker stuff, though it sometimes requires to restart the webapp a few times after "updates". it's what the previous version of whatsapp in pi-apps used.
```js
if ('serviceWorker' in navigator) {
    caches.keys().then(function (cacheNames) {
        cacheNames.forEach(function (cacheName) {
            caches.delete(cacheName);
        });
    });
} 
```
(I have no idea how it works, I got it from here: https://github.com/nativefier/nativefier/issues/1112#issuecomment-795424961)
also using a firefox or safari user agent helps sometimes.

**Comment by cycool29** [comment]
> @cycool29 the following JS injection code works fine for deleting the service worker stuff, though it sometimes requires to restart the webapp a few times after "updates". it's what the previous version of whatsapp in pi-apps used.
> 
> ```js
> if ('serviceWorker' in navigator) {
>     caches.keys().then(function (cacheNames) {
>         cacheNames.forEach(function (cacheName) {
>             caches.delete(cacheName);
>         });
>     });
> } 
> ```
> 
> (I have no idea how it works, I got it from here: [nativefier/nativefier#1112 (comment)](https://github.com/nativefier/nativefier/issues/1112#issuecomment-795424961))
> also using a firefox or safari user agent helps sometimes.

Some nativefier settings seems not working after second launch sometimes, including `inject` and `user-agent`. 
You can't know whether the JS code has been injected. But my script ensure the `Service Worker` folder deleted before launching WhatsApp ( using && operator ) .

But the weird thing is, the js script seems work in **multi-device beta**. It won't have the prompt like this:

image

Still finding out why.
If it really works, maybe add a prompt in installation script asking users whether they are using normal mode or multi-device beta ( however I think the multi-device function will be merged to the normal mode very soon ).

**Pull request merged**
