### PR TITLE
Add btop 

### PR DESCRIPTION
**Pull request by Crilum**
[btop](https://github.com/aristocratos/btop) is a resource monitor and task manager, run in the terminal. It's similar to htop, but it's a lot more sophisticated.

I think a lot of Pi-Apps users would find this helpful. I have tested it on armhf, but it should work just fine on arm64, the only difference is the .tbz downloaded from the btop repo.

Again, sorry for the extra commits..

### CODE REVIEW

**Comment by Crilum** [comment]
I think the app folder is there... If it isn't there, let me know...

**Comment by Crilum** [comment]
There is only one problem, as far as I can tell. If you quit from the menu, btop freezes, and the only thing you can do to close it is to just exit the terminal. If btop is running normally though, you can just use `ctrl+c`.

**Comment by theofficialgman** [comment]
shouldn't you be using the armv7l version anyway to maintain compatibility with pi0 to pi2? armv7-r is real time and probably won't work as expected on the pis
@Crilum grab the armv7l from the artifact here and check if it has the same problem: https://github.com/aristocratos/btop/suites/4249313140/artifacts/110248933 https://github.com/aristocratos/btop/actions/runs/1418721115

**Comment by Crilum** [comment]
>I can confirm though, btop quit from menu makes btop freeze for me on aarch64 using that build
I imagine this is a btop bug, maybe you should make an issue for it?

Yeah, I will.

>shouldn't you be using the armv7l version anyway to maintain compatibility with pi0 to pi2? armv7-r is real time and probably won't work as expected on the pis

I am using the armvl7r release for armhf, and the aarch64 release for arm64. I will try the armv7lm, as you suggested. Why wouldn't the current armv7lr release work on Raspberry Pi 0 - 2? It's all armhf.

**Comment by Crilum** [comment]
The armv7lm install works exactly the same.. What is the difference? I don't see why one should be used over the other. :)

**Comment by Crilum** [comment]
You can also quit by pressing `q`, but it still has the problem when you quit from menu..

**Comment by cycool29** [comment]
> You can also quit by pressing `q`, but it still has the problem when you quit from menu..

Not for me. I can quit very well with menu (both using ENTER and double-click) BUT *sometimes* it will hang, but not often.

**Comment by Crilum** [comment]
@cycool29 hmm that's odd. Are you on a Pi 4?

@aristocratos fixed the `QUIT` freezing problem, here are the automatically built debs, of which there are a lot more arm versions than the normal releases: [`armv7lr`](https://github.com/aristocratos/btop/suites/4286979610/artifacts/111686795), [`armv7lm`](https://github.com/aristocratos/btop/suites/4286979610/artifacts/111686794), and [`aarch64`](https://github.com/aristocratos/btop/suites/4286979610/artifacts/111686782)

There is also a [`armv7l`](https://github.com/aristocratos/btop/suites/4286979610/artifacts/111686793) build, which might be better.. No `r` or `m`.

The rolling releases are actually just a single executable, so I'm going to rewrite the install scripts, but the problem is fixed.

**Comment by Crilum** [comment]
I also made a PR to upload the files to Pi-Apps-Coders/files, because wget couldn't download them from the above links.

**Comment by theofficialgman** [comment]
@Crilum btw, you most certainly can download directly from the releases page. you shouldn't be re-hosting those files
```
curl https://api.github.com/repos/ChristopherHX/linux-packaging-scripts/releases/latest | grep "browser_download_url.*Launcher-$type" | cut -d : -f 2,3 | tr -d \" | wget -i -
```
```

**Comment by theofficialgman** [comment]
and wget works just fine for the releases page of btop
```
wget https://github.com/aristocratos/btop/releases/download/v1.0.22/btop-1.0.22-aarch64-linux-musl.tbz
```

**Comment by Crilum** [comment]
> and wget works just fine for the releases page of btop
> 
> ```
> wget https://github.com/aristocratos/btop/releases/download/v1.0.22/btop-1.0.22-aarch64-linux-musl.tbz
> ```

Yes, but I'm talking about the [rolling releases](). wget dosen't work with links like this this:

```
wget https://github.com/aristocratos/btop/suites/4286979610/artifacts/111686793
```

**Comment by theofficialgman** [comment]
oh I see you want the artifacts from the latest commit...
yeah you have to use the github api for that

**Comment by theofficialgman** [comment]
just wait a couple of days
btop releases a new version to their release page about twice a week

**Comment by aristocratos** [comment]
@theofficialgman @Crilum 
Will push a release later today, I can include armv7l in the release packages if you want?

**Comment by theofficialgman** [comment]
> @theofficialgman @Crilum Will push a release later today, I can include armv7l in the release packages if you want?

that would be nice! It seems to me that armv7l is what all the distros are packaging these days for using in their arm32 bit releases. armv7-r doesn't seem like the right release to use at least for this install script

**Comment by aristocratos** [comment]
I think I got it mixed up when setting up the release script, `armv7l` should have been included while `armv7r` and `armv7m` should have been left to the auto build.

Musl seem to have only a `hf` version of the toolchain for `armv7l` so not much choice there.

**Comment by theofficialgman** [comment]
yeah thats good. debian uses the hf version which is what I was saying. so thats exactly what we want anyway

**Comment by aristocratos** [comment]
[v1.0.23](https://github.com/aristocratos/btop/releases/tag/v1.0.23) released with fixed menu bug and static armv7l binary included.

**Comment by theofficialgman** [comment]
not ready for merge
wait a bit as I discovered 2 bugs in btop that are being fixed as we speak

**Comment by Crilum** [comment]
Ok, what are they?

**Comment by theofficialgman** [comment]
https://github.com/aristocratos/btop/issues/143
https://github.com/aristocratos/btop/issues/144

**Comment by Crilum** [comment]
Once @aristocratos authors another release with the latest fix, I think it should be good to merge.

**Comment by Crilum** [comment]
@theofficialgman, @aristocratos needs confirmation that the latest automatic build works before he can make another release. Can you test it?

**Comment by Crilum** [comment]
@aristocratos released another version of btop, so I'll update the scripts.

**Comment by theofficialgman** [comment]
@Crilum please do read up on how to squash your commits and force push to your branch...
its good to get to know the git commands or whatever git GUI you might be using

**Comment by Crilum** [comment]
I think I'm going to delete my fork, create a new one, and upload my apps correctly.. Is that a good idea?

**Comment by theofficialgman** [comment]
I promise you git is not that hard to learn
assuming you have your git branch checked out locally
but if thats easier I guess thats fine

**Comment by Botspot** [comment]
I've added `terminal-run` functionality. It's based on the implementation found in the **All Is Well** app.

**Comment by theofficialgman** [comment]
@Botspot why use terminal-run and depend on pi-apps being installed?
whats wrong with this?

```
[Desktop Entry]
Name=btop++
GenericName=System Monitor
Comment=Awesome terminal resource monitor and task manager, similar to htop.
Exec=btop'
Icon=$(dirname "$0")/icon-64.png
Terminal=true
StartupNotify=true
Type=Application
Categories=Utility;"
```

**Comment by theofficialgman** [comment]
also lol... why didn't you squash on merge botspot
now the pi-apps git history is so ugly with all the merge commits from Crilum 😆

**Comment by theofficialgman** [comment]
here is my reasoning for now having `terminal-run` in .desktop files:
lets say the user uninstalls pi-apps, suddenly all their .desktop files stop working because terminal-run isn't found (its gone missing due to pi-apps folder getting removed

I don't think removing pi-apps should affect the functionality of the apps it installs
I understand that you won't be getting the name of the app at the top of the terminal, but thats a sacrifice I'm willing to take (htop in its official install still says Terminal at the top)

**Comment by Botspot** [comment]
> also lol... why didn't you squash on merge botspot now the pi-apps git history is so ugly with all the merge commits from Crilum 😆

I merge PRs using the web client, and I'm not aware of a way to squash commits from there.

**Comment by theofficialgman** [comment]
I thought the web client had a drop down on the Merge button
that let you select merge and squash

**Comment by theofficialgman** [comment]
```
**Squash and merge your pull request commits**
When you select the Squash and merge option on a pull request on GitHub.com, the pull request's commits are squashed into a single commit. Instead of seeing all of a contributor's individual commits from a topic branch, the commits are combined into one commit and merged into the default branch. Pull requests with squashed commits are merged using the fast-forward option.
```
from github documentation, yes it does

**Comment by Botspot** [comment]
> here is my reasoning for not having `terminal-run` in .desktop files: lets say the user uninstalls pi-apps, suddenly all their .desktop files stop working because terminal-run isn't found (its gone missing due to pi-apps folder getting removed)
> 
> I don't think removing pi-apps should affect the functionality of the apps it installs I understand that you won't be getting the name of the app at the top of the terminal, but thats a sacrifice I'm willing to take (htop in its official install still says Terminal at the top)

The reason **All is Well** uses terminal-run is because we had some discord users saying that `Terminal=true` wasn't working on their system. I don't know why the terminal wasn't launching on their system, but once we switched to terminal-run it magically started working for them.
This design decision was simply extended to btop. (Also it's used for the Zoom app)

Every decision needs to weigh the advantages and disadvantages.

- Advantages: apps would be able to run, even if pi-apps is uninstalled.
- Disadvantages: loss of terminal-titles and risk of creating additional, unreproducible runtime issues.

**Comment by theofficialgman** [comment]
> Every decision needs to weigh the advantages and disadvantages.
> 
> * Advantages: apps would be able to run, even if pi-apps is uninstalled.
> * Disadvantages: loss of terminal-titles and risk of creating additional, unreproducible runtime issues.

well terminal=true not working for them would cause a lot of other problems....
like the official install for htop not working, as well as pretty much every other terminal application that gives a .desktop icon

**Comment by Botspot** [comment]
> well terminal=true not working for them would cause a lot of other problems

True, but it seems to happen.

Basically, I don't want to cause a hard problem by solving an easy problem.
Perhaps if someone was interested enough, they could create a PR that copies the terminal-run script out of the pi-apps folder and uses that for the desktop file?

**Comment by theofficialgman** [comment]
> True, but it seems to happen.
do you happen to have a link to that happening in the discord?
I can't find any reference to that myself

**Comment by Botspot** [comment]
> do you happen to have a link to that happening in the discord? I can't find any reference to that myself

That will be hard to find. But [this commit](https://github.com/Botspot/pi-apps/commit/d898407b036115312fbd10aef6598ed6a00d7810) is the day when I made the change, so that might help us find it.

**Comment by Crilum** [comment]
Maybe helpful: 
https://askubuntu.com/questions/436891/create-a-desktop-file-that-opens-and-execute-a-command-in-a-terminal

My btop desktop file is set to `terminal=false` and I think that is the way it should be. It just opens btop alone.
With `terminal=true`, it opens a blank terminal, and btop:

2021-11-12-113602_2560x1440_scrot

**Comment by theofficialgman** [comment]
> My btop desktop file is set to `terminal=false` and I think that is the way it should be. It just opens btop alone. With `terminal=true`, it opens a blank terminal, and btop:

@Crilum you don't understand the argument here... you are doing it wrong.
you shouldn't use terminal=true if `terminal-run` is used in the exec line

if you just launch btop in the exec line like below, then you open a terminal with btop in it, without all the fancy window decorations, etc
```
[Desktop Entry]
Name=btop++
GenericName=System Monitor
Comment=Awesome terminal resource monitor and task manager, similar to htop.
Exec=btop
Icon=$(dirname "$0")/icon-64.png
Terminal=true
StartupNotify=true
Type=Application
Categories=Utility
```

**Pull request merged**
