### PR TITLE
Add a few badges to the README

### PR DESCRIPTION
**Pull request by ryanfortner**

### CODE REVIEW

**Comment by cycool29** [comment]
I think we can also add the License badge: https://img.shields.io/github/license/Botspot/pi-apps.

**Comment by ryanfortner** [comment]
> I think we can also add the License badge: https://img.shields.io/github/license/Botspot/pi-apps.

Added.

**Comment by cycool29** [comment]
@ryanfortner

**Review by cycool29 — CHANGES_REQUESTED** [review]

**Comment by theofficialgman** [comment]
rebased to solve conflicts

**Comment by theofficialgman** [comment]
@Botspot I think this looks nice, you can preview the readme changes here https://github.com/Botspot/pi-apps/blob/6f5b01828fac1d281e0bb55330b39e50f970a191/README.md

**Comment by Botspot** [comment]
I know it;s a bit silly, but is there any way to make the spaces between the badges to not be hyperlinks? The tiny bit of underline that appears between each badge bothers me.
https://user-images.githubusercontent.com/54716352/151718532-b6d852d4-788d-4743-bdd0-d5f73b7aab02.mp4

**Comment by theofficialgman** [comment]
@Botspot fixed with https://github.com/Botspot/pi-apps/pull/1210/commits/e5f4912bd23c50b170d1ce3ac08e666c75412591

**Comment by Botspot** [comment]
Much better. :)

**Pull request merged**
