### PR TITLE
make MacOS theme uninstall script executable. fixes #419

### LINKED ISSUE #419: Can't Uninstall Mac OS Theme
I was tried to uninstall Mac OS Theme because the installed failed. I need to uninstall it but I get this error

```
Uninstalling Mac OS Theme
/home/pi/pi-apps/apps/Mac OS Theme/uninstall: line 11: /home/pi/.local/share/MacOSBigSurThemeConverter/uninstall.sh: Permission denied

Failed to uninstall Mac OS Theme!

Close this window to exit.



```

### PR DESCRIPTION
**Pull request by Itai-Nelken**

### CODE REVIEW

**Comment by Dell-Glitch** [comment]
It looks executable, what do you mean by executable?

**Comment by Dell-Glitch** [comment]
enter sudo chmod +x ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh in terminal then try to uninstall it

**Comment by Itai-Nelken** [comment]
> enter sudo chmod +x ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh in terminal then try to uninstall it

???
this is what this pr fixes.

**Comment by Dell-Glitch** [comment]
so it's fixed? I was looking in install script and some install.sh script needed to be chmod +x so i thought it would work for ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh

**Comment by Itai-Nelken** [comment]
> so it's fixed? I was looking in install script and some install.sh script needed to be chmod +x so i thought it would work for ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh

this is a pr (Pull Request), that means I forked (made a copy) of the main pi-apps repo. made the uninstall script for MacOS theme make `~/.local/share/MacOSBigSurThemeConverter/uninstall.sh` executable (`sudo chmod +x ~/.local/share/MacOSBigSurThemeConverter/uninstall.sh`), and now I'm "asking" Botspot to merge this into the main repo so its available for everyone.

what you say is correct, and will fix the issue, but this is not a bug report this is a fix for the bug report (#419 ).

**Comment by Dell-Glitch** [comment]
ok

**Pull request merged**
