### PR TITLE
Steam: remove install-32 and add install-64

### PR DESCRIPTION
**Pull request by theofficialgman**
closes https://github.com/Botspot/pi-apps/pull/653 closes https://github.com/Botspot/pi-apps/issues/1481

depends on https://github.com/Botspot/pi-apps/pull/2275

### CODE REVIEW

**Comment by Botspot** [comment]
What was the rationale behind removing install-32? Was this a result of recent Steam changes that make it incompatible with box86?

**Comment by theofficialgman** [comment]
> What was the rationale behind removing install-32? Was this a result of recent Steam changes that make it incompatible with box86?

@Botspot please refer to the recent commit on the pi-apps repo https://github.com/Botspot/pi-apps/commit/60a8b0c26c80f569840f4793aaf0e62c4f5cb9cd

**Comment by Botspot** [comment]
Test successful on PiOS 64-bit.
At least, I reached the sign-in screen.

To avoid the perception that Pi-Apps updates cause regressions, I want to look into the whole chroot realm again to see how feasible it is here. This would also help bring flatpaks back to armhf.
If others test this PR more thoroughly, I am not opposed to merging it, since existing 32-bit steam installs will remain unchanged.

**Comment by theofficialgman** [comment]
> To avoid the perception that Pi-Apps updates cause regressions, I want to look into the whole chroot realm again to see how feasible it is here.

I don't think it is feasable. since it requires more than 4GB of ram. there is a possibility that you run out of ram that a 32bit kernel can allocate to one process. that wouldn't be an issue with a 64bit kernel on a 32bit userspace though with a 64bit chroot. But I honestly just think that is madness. There really are no legitimate reasons to be using a 32bit OS in 2023. Multiarch works on PiOS bullseye. if there is any software that requires 32bit userspace, it can work in that.

**Comment by theofficialgman** [comment]
> Test successful on PiOS 64-bit. At least, I reached the sign-in screen.

reaching the sign in screen is enough of a test. the sign in screen is CEF (chromium embedded framework) in a react window. if it works, then everything else will.

**Comment by Botspot** [comment]
I was able to sign in today and everything seemed to work okay.

**Comment by theofficialgman** [comment]
intentional by steam (couldn't find the original post, only a screenshot from a discord user): https://cdn.discordapp.com/attachments/700827460454973522/1070478345336270888/Screenshot_2023-02-01-23-58-02-910-edit_com.valvesoftware.android.steam.community.jpg

**Pull request merged**
