### PR TITLE
Create install-64 / -32 & uninstall file update

### PR DESCRIPTION
**Pull request by fabianmendes**
dependences missed. Related issue #401

### CODE REVIEW

**Review by fabianmendes — COMMENTED** [review]
Ok, I've forgotten to include all these dependences on the unistall file!

**Comment by fabianmendes** [comment]
done. @Botspot  [Remarkable.zip](https://github.com/Botspot/pi-apps/files/6058509/Remarkable.zip)

**Comment by Botspot** [comment]
Seen and tested.

`install-32` works for me, but I'm not too thrilled with these new lines in the `uninstall` script:
```
sudo apt purge gir1.2-webkit -y || error "Failed to purge gir1.2-webkit pacakge!"
sudo apt purge gir1.2-javascriptcoregtk -y || error "Failed to purge gir1.2-javascriptcoregtk pacakge!"
sudo apt purge libwebkitgtk -y || error "Failed to purge libwebkitgtk pacakge!"
sudo apt purge libjavascriptcoregtk -y || error "Failed to purge libjavascriptcoregtk pacakge!"
sudo apt purge libicu57* -y || error "Failed to purge libicus57 pacakge!"
```
What if somebody already installed one of those packages? What if removing one of those packages also purges a bunch of other packages?  
That would be a bad day for everyone involved.

**Comment by fabianmendes** [comment]
Is that possible to create uninstall-64?? How can I manage that?

Also, good point. Thanks @Botspot

**Comment by Itai-Nelken** [comment]
>Is that possible to create uninstall-64?? How can I manage that?

make the uninstall script detect what architecture you are on, maybe something like this:
```bash
if [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 64)" ];then
    #COMMANDS TO UNINSTALL 64BIT
elif [ ! -z "$(file "$(readlink -f "/sbin/init")" | grep 32)" ];then
    #COMMANDS TO UNINSTALL 32BIT
else
    error "Failed to detect OS CPU architecture! Something is very wrong."
fi
```
(make sure you are using the pi-apps template or have the error function)

**Comment by Botspot** [comment]
Closing this PR. Any further discussion will be had at #401.

**Pull request closed without merging**
