### PR TITLE
Loads of changes to descriptions and credit files

### PR DESCRIPTION
**Pull request by CleanMachine1**
I have worked for around 45 mins to try and standardise the files:

Capitalising first words
Lines when lines get too long/unrelated lines
And much more

### CODE REVIEW

**Comment by Botspot** [comment]
Wow.
Looks like somebody has a taste for good grammar! Thanks!

I've made a couple tweaks in a few cases where you missed something, or where I felt that changing the sentence back would display better.

**Comment by CleanMachine1** [comment]
The exclamation point should be after the (text).

**Comment by Botspot** [comment]
> The exclamation point should be after the (text).

Yes I know: grammatically that's correct, but in this case the text was being wrapped. Additionally, if you read it aloud, the wrong part of the sentence is emphasized in my opinion.  
This seemed like a case where it's technically wrong, but to the average user, it improves the experience. Because in the end, that's what matters.

**Comment by CleanMachine1** [comment]
Also I like perfect documentation, its annoying to read something that doesn't make sense!

**Pull request merged**
