### PR TITLE
Add Telegram app

### PR DESCRIPTION
**Pull request by cycool29**
Actually installable with `apt`, but just hope to have a more convenient way to install it.

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
Apt version is old and isn't fully functional.
Also as those scripts simply install the apt version, I don't think this should be added.
Also about telegram see #156

**Comment by cycool29** [comment]
I don't know why, all `armhf` deb after version `1.5.11` [here](http://ftp.us.debian.org/debian/pool/main/t/telegram-desktop/) will popup error with a long dependencies hell. I think the only way to install Telegram desktop with full features and best performance is to install `snapd` as dependencies in pi-apps script.

**Comment by Itai-Nelken** [comment]
@cycool29 could you try to use the flatpak version instead of the snap?
snapd seems to have a lot of problems installing on some systems, at least according to the pi-apps error reports.
so using flatpak is a better choice in my opinion. also I find flatpak's slightly faster than snaps.

**Comment by cycool29** [comment]
> @cycool29 could you try to use the flatpak version instead of the snap?
> snapd seems to have a lot of problems installing on some systems, at least according to the pi-apps error reports.
> so using flatpak is a better choice in my opinion. also I find flatpak's slightly faster than snaps.

Done. Ya, it is slightly faster than snap one.

**Comment by Itai-Nelken** [comment]
There is a problem with adding a desktop shortcut as flatpak already does that but it won't show until a reboot.
So maybe add a script to remove the one the `install` script creates on reboot (with cron maybe?) and then delete itself.

**Comment by cycool29** [comment]
Actually flatpak store its desktop shortcut in `/var/lib/flatpak/app/org.telegram.desktop/current/active/export/share/applications/org.telegram.desktop.desktop` , but I don't know why it won't appear in the menu even after reboot.  But copying it to `~/.local/share/applications` and change the icon (as the system can't detect the icon without modifying `XDG_DATA_DIR` variable). So I will just add that in the script.

**Comment by Itai-Nelken** [comment]
Thanks. make sure to move it so it won't appear twice for some systems like mine where after a reboot the flatpak one shows up.
if you do that check that the app still uninstall correctly.

**Comment by cycool29** [comment]
Instead of keep `sed`ing the icon and name in the desktop entry, I decided to directly make a new file in `~/.local/share/applications` and echo the full desktop entry in it. 

> Thanks. make sure to move it so it won't appear twice for some systems like mine where after a reboot the flatpak one shows up.

Are you using Raspbian? Mine don't even show up.

**Comment by cycool29** [comment]
Done.
@Itai-Nelken Can you test it?

**Comment by cycool29** [comment]
Done. Works well for me.

**Comment by Botspot** [comment]
@cycool29 I've made a few improvements to the scripts that address a few edge-cases.

**Pull request merged**
