### PR TITLE
Change order of execution

### PR DESCRIPTION
**Pull request by mobilegmYT**

### CODE REVIEW

**Comment by Botspot** [comment]
Have you tested this and are you sure it works?

**Comment by mobilegmYT** [comment]
Yes.

**Comment by Botspot** [comment]
ok

**Comment by mobilegmYT** [comment]
oh wait no....

**Comment by mobilegmYT** [comment]
1 sec

**Comment by mobilegmYT** [comment]
I checked and it worked!

**Comment by Botspot** [comment]
Do you want me to merge this?

**Comment by Botspot** [comment]
Oh I see the new commit now. Merging.

**Pull request merged**
