### PR TITLE
add xfburn package

### PR DESCRIPTION
**Pull request by ryanfortner**
Closes https://github.com/Botspot/pi-apps/issues/1894

### CODE REVIEW

**Comment by theofficialgman** [comment]
@Botspot would you might adding additional "rules" to the rubric specifically regarding package apps. https://github.com/Botspot/pi-apps/issues/185

I have said before that I don't like package apps and don't feel like they really fit pi-apps but that isn't the matter of discussion here (I can just disable them with the settings toggle which is enough for me).

What I would like clarified is what type of package apps should be eligible/included in pi-apps. I feel like we are reaching the point where package apps are becoming a significant portion of the app list and rules for their inclusion should be listed.

**Comment by Botspot** [comment]
> @Botspot would you might adding additional "rules" to the rubric specifically regarding package apps. #185
> 
> I have said before that I don't like package apps and don't feel like they really fit pi-apps but that isn't the matter of discussion here (I can just disable them with the settings toggle which is enough for me).
> 
> What I would like clarified is what type of package apps should be eligible/included in pi-apps. I feel like we are reaching the point where package apps are becoming a significant portion of the app list and rules for their inclusion should be listed.

A bit of background:
I never intended for Pi-Apps to include apt packages. But I also never intended it to be a primary installation method for some users.
What ended up happening was that apps available on apt began having a *disadvantage*.
If a GUI user wants to install an image editor from a curated list of apps (which is what Pi-Apps has become), it would be a shame to only include non-apt apps, while excluding potentially better options just because they were from apt.

There is definitely a potential for this package-app feature to be taken too far. @theofficialgman, if you have any particular package-apps in mind that don't seem to fit, by all means let me know.

**Comment by Crilum** [comment]
The purpose of Pi-Apps is definitely _not_ an Apt GUI..

**Comment by theofficialgman** [comment]
> What ended up happening was that apps available on apt began having a _disadvantage_. If a GUI user wants to install an image editor from a curated list of apps (which is what Pi-Apps has become), it would be a shame to only include non-apt apps, while excluding potentially better options just because they were from apt.

I like this explanation, it makes sense. Given this, do you think it would be a good idea for our "rules" then to say that package apps should only be included if there is already a similar alternative for that package already included in pi-apps?


under this "rule" the xfburn package app would be fine to include because there is similar non-package app software already pi-apps (USBImager)

**Comment by Crilum** [comment]
> there is already a similar alternative for that package already included in pi-apps?

is or isn't?

**Comment by theofficialgman** [comment]
> is or isn't?

is. I think we should only include a package app IF there is already an install(32/64) type software for that in pi-apps. basically, no new random software from package apps that has no pi-apps unique (install32/64) alternative

**Comment by Botspot** [comment]
> I like this explanation, it makes sense. Given this, do you think it would be a good idea for our "rules" then to say that package apps should only be included if there is already a similar alternative for that package already included in pi-apps?

This sounds reasonable to me, though it might make for some silly situations down the road.
For example, a potential app-submitter may try to add a script app for the sole purpose of adding a package-app afterwards.
Or, the app-submitter will make a script-app to install a slightly newer version of an already available apt package, "just because" it's allowed. But I guess this one has already happened a few times. 😂

**Pull request merged**
