### PR TITLE
Pi-apps codebase optimization and functional rewrite in C.

### PR DESCRIPTION
**Pull request by tehfrutcak1**
If you disagree with my edits, don't merge to main. I'm not going to pursue this, I have no interest in further wasting my time with this project. I personally think that pi-apps is a detriment to all beginners in the Raspberry Pi world, teaching them to further depend on GUIs and such, as opposed to learning to think for themselves and:

- Edit their sources.list
- Manually install via `.deb` package
- Compile from source

To reiterate, it is my belief that pi-apps is a detriment to those who wish to learn using the Raspberry Pi SBC. I hope that this joke pull-request moves you to some degree to at least put something of a disclaimer in your `readme.md`. To be blatantly honest, your readme is pompous at best and completely misleading at worst (it's both, actually.) I implore you to teach instead of feeding off of ignorance.

Post-script: The `compile.sh` file is complete garbage on purpose, by the way.

### CODE REVIEW

**Comment by MickTheRus** [comment]
No, this is completely stupid, let the beginners use easier stuff and harder crap later.

**Comment by mobilegmYT** [comment]
Agreed, sometimes it's better if a user learned, but if you told 7-year old me who just got his rpi that I have to use wget and echoing to files and some weird flags just to run minecraft, even if I just had copy and paste terminal commands I'd still be quite overwhelmed with the stuff I'd need to do.

**Comment by Botspot** [comment]
> I personally think that pi-apps is a detriment to all beginners in the Raspberry Pi world, teaching them to further depend on GUIs and such, as opposed to learning to think for themselves
> To reiterate, it is my belief that pi-apps is a detriment to those who wish to learn using the Raspberry Pi SBC.

Without Pi-Apps, very few beginner Pi users have the determination, willpower, and knowledge to get all Pi-Apps apps working.
For example, practically zero beginner users would succeed to install emulated x86 Wine on their Pi3s. Doing so requires them to understand how to:
- Compile box86 and install it.
- Download, compile, and install an x86 version of Wine. (don't forget that `winetricks` workaround!)
- Compile a 3G/1G kernel for the Pi3 and properly apply it.
- Keep all of the above updated and running.
**I have yet to meet a beginner RPi user who could accomplish all of that.** _Even if they were following a tutorial_, there's a good chance they'd mess up somewhere along the line and have no clue how to proceed.
But with Pi-Apps in the picture, any beginner user can install x86 Wine on their Pi3 within _minutes_, instead of hours or days.

Tutorials have their place. Deb files have their place. Compiling from source, bricking your system and learning things the hard way, has its place.
But Pi-Apps has its place too. It has its place for the **millions** of users who'd rather **get stuff done** than **understand how** it's being done.
Pi-Apps has its place for poverty-stricken families who can't afford a real PC, for the children who were given a Raspberry Pi and must use it to do schoolwork, for the grandfather who wants to set up his Pi to do a video call with his loved ones. These people don't need a tutorial. They don't desire a lecture on Linux's inner workings. They don't want a Linux veteran to tell them to use the terminal and run a bunch of stuff.
Instead, they all have a set goal in mind and want to reach that goal as quickly and as efficiently as possible.

> To reiterate, it is my belief that pi-apps is a detriment to those who wish to learn using the Raspberry Pi SBC.

That's the problem right there: Pi-Apps is not intended for hard-core Linux users. It is not intended for those who wish to learn computer skills on the platform. It's for the tens of millions of people who want it to work as a normal, desktop computer.

Thank you for your feedback. Feedback is always welcome. :)

**Comment by AmirDahan** [comment]
Pi apps is a great utility for beginners that dont know how to use linux and or are too lazy to google things on their own
Trust me there is a lot of those ppl in the raspberry pi community
imo having more tools is better than having none
if you dont like pi apps then dont use it , as simple as that

**Comment by Botspot** [comment]
> > I personally think that pi-apps is a detriment to all beginners in the Raspberry Pi world, teaching them to further depend on GUIs and such, as opposed to learning to think for themselves
> > To reiterate, it is my belief that pi-apps is a detriment to those who wish to learn using the Raspberry Pi SBC.
> 
> Without Pi-Apps, very few beginner Pi users have the determination, willpower, and knowledge to get all Pi-Apps apps working.
> For example, practically zero beginner users would succeed to install emulated x86 Wine on their Pi3s. Doing so requires them to understand how to:
> 
> * Compile box86 and install it.
> * Download, compile, and install an x86 version of Wine. (don't forget that `winetricks` workaround!)
> * Compile a 3G/1G kernel for the Pi3 and properly apply it.
> * Keep all of the above updated and running.
> 
> **I have yet to meet a single beginner RPi user who could accomplish all of that on their own.**
> _Even if they were following a tutorial_, there's a good chance they'd mess up somewhere along the line and have no clue how to proceed.
> But with Pi-Apps in the picture, _any_ beginner can install x86 Wine on their Pi3 with **one click**, instead of countless frustrating hours.
> 
> Tutorials have their place. Deb files have their place. Compiling from source, bricking your system and learning things the hard way, has its place.
> But Pi-Apps has its place too. It has its place for the **millions** of users who'd rather **get stuff done** than **understand how** it's being done.
> Pi-Apps has its place for poverty-stricken families who can't afford a real PC, for the children who were given a Raspberry Pi and must use it to do schoolwork, for the grandfather who wants to set up his Pi to do a video call with his loved ones. These people don't need a tutorial. They don't desire a lecture on Linux's inner workings. They don't want a Linux veteran to tell them to use the terminal and run a bunch of stuff.
> Instead, they all have a set goal in mind and want to reach that goal as quickly and as efficiently as possible.
> 
> > To reiterate, it is my belief that pi-apps is a detriment to those who wish to learn using the Raspberry Pi SBC.
> 
> It is not intended for those who wish to learn computer skills on the platform.

But there's nothing wrong with exposing people to the app scripts, if they so choose to click a button.
As of [now](https://github.com/Botspot/pi-apps/commit/85985c0ef45f95546f996982e8b5fd8a7f2805e7), Pi-Apps has a new button added to the App Details page: "Script". Clicking it lets you view (and edit!) the selected app's installation scripts.

**Pull request closed without merging**
