### PR TITLE
- added fish

### PR DESCRIPTION
**Pull request by kkarhan**
- - Source: https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish#manualDebian

### CODE REVIEW

**Comment by kkarhan** [comment]
Added fish Shell installation Scripts
https://fishshell.com/

**Comment by theofficialgman** [comment]
I can't comment on if this fits our app eligibility rubric however I can say that your scripts currently use multiple commands that are not allowed in pi-apps scripts and this PR will not be accepted in it's current state. Please read our documentation on creating an install/uninstall script. In particular the section on do not use apt https://pi-apps.io/wiki/development/Creating-an-app/

**Comment by Botspot** [comment]
@kkarhan, to add to what theofficialgman said, you need to be using our `install_packages` and `purge_packages` functions. Also an app on pi-apps can only either have scripts or a `packages` file. You have both, so please remove the `packages` file.

**Comment by theofficialgman** [comment]
closing as stale since changes have not been implemented after a lengthy period of time

**Pull request closed without merging**
