### PR TITLE
add armcord application

### PR DESCRIPTION
**Pull request by ryanfortner**

### CODE REVIEW

**Comment by theofficialgman** [comment]
@ryanfortner converted to draft due to outdated armcord release build on electron 18.2.3 with bug preventing buster/bionic

**Comment by Botspot** [comment]
The install-32 script seems to be missing. I'm fairly ArmCord works on armhf.

**Comment by ryanfortner** [comment]
> The install-32 script seems to be missing. I'm fairly ArmCord works on armhf.

There are no armhf binaries provided in releases currently, I could try compiling from source though. https://github.com/ArmCord/ArmCord/issues/118

**Comment by ryanfortner** [comment]
Just bumped the version and added `install-32`. This should be good to go.

**Comment by theofficialgman** [comment]
tested on arm64 and the application works but the .desktop icon is missing...

it seems to have installed here:
`/usr/share/icons/hicolor/0x0/apps/armcord.png`

but it does not get used even after rebooting or reloading the cache


the `0x0` directory is very strange as well...

**Comment by theofficialgman** [comment]
tested on arm64 and the application works but the .desktop icon is missing...

it seems to have installed here:
`/usr/share/icons/hicolor/0x0/apps/armcord.png`

but it does not get used even after rebooting or reloading the cache


the `0x0` directory is very strange as well...

**Comment by Crilum** [comment]
Fails to install on armhf:
```
OS: Raspbian GNU/Linux 11 (bullseye)
OS architecture: 32-bit
Last updated Pi-Apps on: 05/31/2022
Latest Pi-Apps version: 05/31/2022
Kernel: aarch64 5.15.32-v8+
Device model: Raspberry Pi 4 Model B Rev 1.2
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2022-01-28
Language: en_US.UTF-8

BEGINNING OF LOG FILE:
-----------------------

nice: ‘/home/pi/pi-apps/apps/ArmCord/install-32’: No such file or directory

Failed to install ArmCord!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

Kind of a weird error..

**Comment by Crilum** [comment]
I think found the problem:
```
$ /home/pi/pi-apps/apps/ArmCord/install-32
bash: /home/pi/pi-apps/apps/ArmCord/install-32: /bin/bash^M: bad interpreter: No such file or directory
```

@ryanfortner It looks like you edited the script with a weird text editor..

**Comment by theofficialgman** [comment]
I changed the line ending to be LF, might work now

**Comment by Crilum** [comment]
Yeah, it works now.

**Comment by theofficialgman** [comment]
I notified upstream of the icon issue. appears to be an electron builder oversight or bug, they will try to fix tomorrow and then make another release.

lets hold off on this a bit longer

**Comment by ryanfortner** [comment]
> I think found the problem:
> 
> ```
> $ /home/pi/pi-apps/apps/ArmCord/install-32
> bash: /home/pi/pi-apps/apps/ArmCord/install-32: /bin/bash^M: bad interpreter: No such file or directory
> ```
> 
> @ryanfortner It looks like you edited the script with a weird text editor..

That's weird, I was using the built-in github [vscode editor](https://github.com/github/dev)...

**Comment by Crilum** [comment]
It's weird that the ArmCord icon is `1280x1280`, yet it's in the `0x0` folder:
image

**Comment by Crilum** [comment]
> > I think found the problem:
> > ```
> > $ /home/pi/pi-apps/apps/ArmCord/install-32
> > bash: /home/pi/pi-apps/apps/ArmCord/install-32: /bin/bash^M: bad interpreter: No such file or directory
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @ryanfortner It looks like you edited the script with a weird text editor..
> 
> That's odd, I was using the built-in github [vscode editor](https://github.com/github/dev)...

The one online? Maybe it expects you're using Windows (lol, probably not..), and that's just the default..

**Comment by Crilum** [comment]
I found the setting for it:
github-dev-line-ending

**Comment by theofficialgman** [comment]
upstream kept the same release number but the deb is fixed now

**Comment by Botspot** [comment]
I just tested this, and my only complaint is that the taskbar icon is unset, so it displays the generic "program" icon.
Last year, I asked SpacingBat3 how to set the icon in an Electron app, and he said to call `BrowserWindow()` with `{icon: "/path/to/icon"}`.
@smartfridge

**Comment by theofficialgman** [comment]
armcord does this already, I think the problem is the path is wrong for deb installs. that icon location doesn't exist https://github.com/ArmCord/ArmCord/blob/40d743d0e21e2b61659b9497ca4bb0e42b811b63/src/window.ts#L116-L147

**Comment by theofficialgman** [comment]
> I just tested this, and my only complaint is that the taskbar icon is unset, so it displays the generic "program" icon. Last year, I asked SpacingBat3 how to set the icon in an Electron app, and he said to call `BrowserWindow()` with `{icon: "/path/to/icon"}`. @smartFridge

also btw, I don't have this problem. taskbar icon is correctly set

**Comment by Crilum** [comment]
@Botspot Which icon do you mean? The taskbar icon is correct, but the window icon is missing:
armcordIcon

**Comment by Botspot** [comment]
> @Botspot Which icon do you mean? The taskbar icon is correct, but the window icon is missing: armcordIcon

the system tray icon works for me, but the taskbar icon/program icon does not work.

> also btw, I don't have this problem. taskbar icon is correctly set

That is to be expected on Ubuntu. Ubuntu DE uses the menu entry's icon if one is not set. I personally think this decision harmed the rest of the linux community, because it reduced the incentive to build apps right.
If worst comes to worst, it's possible to make a wrapper script with some `xseticon` magic like I did with Boxy SVG, but I'd rather it just be done right in the source code.

**Comment by theofficialgman** [comment]
> @theofficialgman, that is to be expected on Ubuntu. Ubuntu DE uses the menu entry's icon if one is not set. I personally think this decision harmed the rest of the linux community, because it reduced the incentive to build apps right.

I assume you mean gnome (Ubuntu has no control over them) or unity. I was testing on budgie so I will have to check on lxde to see if that's the case

**Comment by smartfrigde** [comment]
image
Seems to be fixed, I'll double check on other DEs tho

**Comment by Botspot** [comment]
> image Seems to be fixed, I'll double check on other DEs tho. The fix will be on the dev branch which means it'll be either in newer release (which will take a while) or I can backport it to 3.0.6

@smartfrigde Whether you would rather wait or backport, it is up to you.
You can also say if you want ArmCord added to Pi-Apps before the program icon works correctly on Raspberry Pi OS. I wouldn't recommend this, but that's your choice.

**Comment by Sussy-OS** [comment]
I can't wait till this app comes! I mean, WebCord is good, but you cannot mod it like you can with ArmCord. 😄

**Comment by Botspot** [comment]
On a similar note to @Sussy-OS's comment, I recently noticed that WebCord's menubar no longer disappears when pressing the Alt key.

**Comment by smartfrigde** [comment]
v3.0.7 is ready with the icon fix ;)

**Comment by theofficialgman** [comment]
@smartfrigde sorry this can't be merged
electron's current 19 releases are broken on arm64 buster/bionic
https://github.com/ArmCord/ArmCord/blob/9efce82462bee62b5b9f74942ecd94936841e5e1/package.json#L29

see: https://github.com/Botspot/pi-apps/issues/1930

we are still waiting on 19.0.5 to release, the fix is already in the electron 19.x.y branch

**Comment by smartfrigde** [comment]
Once 19.0.5 releases I'll re-do the release and notify you here.

**Comment by smartfrigde** [comment]
[Done.](https://github.com/ArmCord/ArmCord/releases/tag/v3.0.7)
image

**Comment by theofficialgman** [comment]
@Botspot merge whenever you get the chance to add the bitly links

**Comment by Sussy-OS** [comment]
How is this open, yet ArmCord is added?

**Pull request merged**
