### PR TITLE
Remove unnecessary lines in PiKISS GUI install

### PR DESCRIPTION
**Pull request by Jai-JAP**
Removed lines that were previously used to remove countdown and output errors as it is no longer required and causes install errors

### CODE REVIEW

**Comment by Jai-JAP** [comment]
@Botspot can you review the app as I added a new feature that displays app's description as a tooltip on hover
I'm pretty sure that there are no bugs but still to confirm

**Comment by Botspot** [comment]
What's this?
```
Syncing Apps with PiKISS...


.
.
.
.
.
.
.
.
.
.

PiKISS Apps successfully synced.
```
Why all those empty lines?

**Comment by Jai-JAP** [comment]
> What's this?
> 
> ```
> Syncing Apps with PiKISS...
> 
> 
> .
> .
> .
> .
> .
> .
> .
> .
> .
> .
> 
> PiKISS Apps successfully synced.
> ```
> 
> Why all those empty lines?

That is intended indicating progress

**Comment by Jai-JAP** [comment]
Botspot did you try the app

**Comment by Botspot** [comment]
> Botspot did you try the app

Yes. It worked fine.

**Comment by Jai-JAP** [comment]
Were the tooltips alright

**Comment by Botspot** [comment]
> Were the tooltips alright

Yep. Only problem I noticed was that on first launch, nothing appeared in the list, even though Internet was selected by default.
For me to view the items in the Internet category, I had to select another category, *then* go back to the Internet category.

**Comment by Botspot** [comment]
> > > Were the tooltips alright
> > 
> > 
> > Yep. Only problem I noticed was that on first launch, nothing appeared in the list, even though Internet was selected by default. For me to view the items in the Internet category, I had to select another category, _then_ go back to the Internet category.
> 
> I am aware of this issue but cant find a way out of it

It's not a big deal. In some ways, this could actually improve the user-experience, to force the user to choose a category first.

**Comment by Jai-JAP** [comment]
> > > > Were the tooltips alright
> > > 
> > > 
> > > Yep. Only problem I noticed was that on first launch, nothing appeared in the list, even though Internet was selected by default. For me to view the items in the Internet category, I had to select another category, _then_ go back to the Internet category.
> > 
> > 
> > I am aware of this issue but cant find a way out of it
> 
> It's not a big deal. In some ways, this could actually improve the user-experience, to force the user to choose a category first.

@Botspot This is done can you test it for one last time.
It now forces user to choose the category first

**Pull request merged**
