### PR TITLE
Fix grammatical error in XMRig install script

### PR DESCRIPTION
**Pull request by Crilum**
Probably don't merge this until a bigger change has to be made, or the auto-updater updates the version, so we don't unnecessarily trigger updates.

Also, I don't mind if this never gets merged. I just noticed a couple things to make the logging prettier, and... :man_shrugging:

### CODE REVIEW

**Comment by Botspot** [comment]
I had seen somewhere some xmrig devs referring to this as XMRig when the name was being used as a title. Same as us using `pi-apps` and `Pi-Apps` interchangeably.
It was a while back though, and it's possible I just made up the capitalized XMRig word usage. I'd recommend looking at xmrig documentation to see if they always spell it lowercase, or only capitalize the first letter, or capitalize the first three. 
Which by the way makes sense as the actual Monero cryptocurrency has codename XMR, just as Bitcoin's codename is BTC.

**Comment by Crilum** [comment]
Seems like `XMRig` is the official name:

image
image
(from https://xmrig.com)

**Comment by theofficialgman** [comment]
>  or the auto-updater updates the version

well actually I had to disable the auto-updater for xmrig because the xmrig install requires user action and our auto-updater is a computer, not a person, and is incapable of providing this user action 🤖 

if you change the version to latest and find that it is still able to be built and run you are welcome to add that to this PR and we can merge afterwards.

**Comment by Crilum** [comment]
> if you change the version to latest `v6.20.0-mo1` and find that it is still able to be built and run you are welcome to add that to this PR and we can merge afterwards.

Okay. I'll try building with the newest version (in qemu, if it works it's probably a good idea to have someone with an actual Raspberry test it).
Also.. What's the `-mo1` part at the end of the version number? I don't see it on the GitHub Releases..
image

**Comment by theofficialgman** [comment]
> Okay. I'll try building with the newest version (in qemu, if it works it's probably a good idea to have someone with an actual Raspberry test it). Also.. What's the `-mo1` part at the end of the version number? I don't see it on the GitHub Releases.. image

looks like you are on the wrong repo. refer to the install script for `MoneroOcean/xmrig`

**Comment by Botspot** [comment]
Closing this PR as there is nothing to merge. If there is further progress building the latest version, it would be better to discuss that in a new issue.

**Pull request closed without merging**
