### PR TITLE
Add PyChess

### LINKED ISSUE #1898: PyChess
### What is the name of the app?

PyChess

### (Optional) Where is the app hosted?

_No response_

### About the app

_PyChess is a gtk chess client, originally developed for GNOME, but running well under all other linux desktops. (Which we know of, at least). PyChess is 100% python code, from the top of the UI to the bottom of the chess engine, and all code is licensed under the GNU Public License.

The goal of PyChess is to provide an advanced chess client for linux following the GNOME Human Interface Guidelines. The client should be usable to those new to chess, who just want to play a short game and get back to their work, as well as those who wants to use the computer to further enhance their play._

https://pychess.github.io/
This is package-app.
[PyChess.zip](https://github.com/Botspot/pi-apps/files/8787072/PyChess.zip)

There is also a new release on GitHub which is workable (Debian 10/11 32bit). If you add this, you can take the deb from there.
https://github.com/pychess/pychess/releases/tag/1.0.3

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

### PR DESCRIPTION
**Pull request by Crilum**
For @Rak1ta's App Request - closes #1898 

This installs the latest version from GitHub (`1.0.3`), as opposed to @Rak1ta's app which just installs the apt version (`1.0.0-1.2`).

This also has an update script.

@theofficialgman Are update scripts supposed to have a `pi_apps_ver`/`_64`/`_32` variable, like the [docs](https://github.com/Botspot/pi-apps/blob/master/.github/workflows/update_github_script.sh#L12-L27) say?

### CODE REVIEW

**Comment by cycool29** [comment]
> @theofficialgman Are update scripts supposed to have a pi_apps_ver/_64/_32 variable, like the [docs](https://github.com/Botspot/pi-apps/blob/master/.github/workflows/update_github_script.sh#L12-L27) say?

No. The script already [does it](https://github.com/Botspot/pi-apps/blob/master/.github/workflows/update_github_script.sh#L50-L60).

**Comment by Crilum** [comment]
> > @theofficialgman Are update scripts supposed to have a pi_apps_ver/_64/_32 variable, like the [docs](https://github.com/Botspot/pi-apps/blob/master/.github/workflows/update_github_script.sh#L12-L27) say?
> 
> No. The `update_github_script.sh` already [does it](https://github.com/Botspot/pi-apps/blob/master/.github/workflows/update_github_script.sh#L50-L60).

Thanks.

**Comment by theofficialgman** [comment]
> @theofficialgman Are update scripts supposed to have a `pi_apps_ver`/`_64`/`_32` variable, like the [docs](https://github.com/Botspot/pi-apps/blob/master/.github/workflows/update_github_script.sh#L12-L27) say?

You can specify them but there is no need to and you really shouldn't as @cycool29 said, the script itself will automatically populate the variables as necessary.

Everything you have committed is correct.

**Comment by Botspot** [comment]
Just played my first match with Stockfish! (and lost)

**Pull request merged**
