### PR TITLE
Add AntiMicroX

### PR DESCRIPTION
**Pull request by Crilum**
Found @ryanfortner's [building instructions](https://github.com/ryanfortner/pi-bashscripts-files/blob/main/AntiMicroX.md) and used them (sort of) to make a Pi-App!

[AntiMicroX](https://antimicrox.github.io/) is a controller mapping software, which you can use to play games like Minecraft Java with a controller.

P.S. Sorry for all the commits, this is what happens when you're a GitHub noob and you make a PR from main... :man_facepalming:

### CODE REVIEW

**Comment by Crilum** [comment]
@Botspot @cycool29 @theofficialgman Any thoughts?

**Comment by theofficialgman** [comment]
> Found @ryanfortner's [building instructions](https://github.com/ryanfortner/pi-bashscripts-files/blob/main/AntiMicroX.md) and used them (sort of) to make a Pi-App!
> 
> [AntiMicroX](https://antimicrox.github.io/) is a controller mapping software, which you can use to play games like Minecraft Java with a controller.
> 
> P.S. Sorry for all the commits, this is what happens when you're a GitHub noob and you make a PR from main... 🤦‍♂️

minecraft java is a bad usecase for this software. though we do have it in the l4t-megascript

minecraft java can be used with `controllable` for forge, and `lambdacontrols` for fabric

**Comment by Crilum** [comment]
Sorry.. Just needed a generic game to make an example of. It's not just limited to Minecraft. :+1:

**Comment by theofficialgman** [comment]
@Crilum fyi, if you use github desktop to manager your repos, its quite easy to squash all your commits into one and then force push over

**Comment by theofficialgman** [comment]
https://github.com/shiftkey/desktop
here is the fork of github desktop for linux... not sure if anyone has build for armhf/arm64 yet
might be an interesting pi-apps script for the future

**Comment by Crilum** [comment]
Desktop doesn't have arm releases..

**Comment by ryanfortner** [comment]
> https://github.com/shiftkey/desktop
> 
> here is the fork of github desktop for linux... not sure if anyone has build for armhf/arm64 yet
> 
> might be an interesting pi-apps script for the future

Never got it to build successfully...

**Comment by Crilum** [comment]
Yeah.. I don't like npm.. I can never get it to work...

**Comment by Crilum** [comment]
Back to AntiMicroX, good for Pi-Apps?

**Comment by theofficialgman** [comment]
maybe considering checking out a specific tag/release version?
otherwise if master breaks for any reason or has bugs, the user will be left with a broken install and no easy way to update

so add a `git checkout 3.2.0` to checkout the 3.2.0 tag
that way we can update that number in pi-apps whenever a new stable release is available

ultimately something like discussed here should be used in pi-apps but no code exists yet, just discussion: https://github.com/Botspot/pi-apps/issues/1019

**Comment by Crilum** [comment]
Yeah, that's a good idea. I've updated `install`.

**Comment by Crilum** [comment]
@theofficialgman @Botspot Any other things you can think of/find that need to be changed, or is this ready to be merged?

**Comment by theofficialgman** [comment]
personally I would put antimicrox under tools and not games like you did `AntiMicroX|Games`

**Comment by Crilum** [comment]
Yeah, and I realized that the desktop file is in `Accessories`, so I'll change that.

**Comment by Crilum** [comment]
Works on Bullseye, BTW.

**Comment by Crilum** [comment]
I think this is ready to be merged..

**Comment by Crilum** [comment]
Thanks @Botspot!

**Comment by theofficialgman** [comment]
@Botspot you forgot about squash and merge didn’t you?.... 35 more ugly commits in the history now

**Comment by Botspot** [comment]
> @Botspot you forgot about squash and merge didn’t you?.... 35 more ugly commits in the history now

Oh no, not again! lol. Is there a way to undo commits?

**Comment by Crilum** [comment]
It looks to me like there is a revert button on the right side of the `merged` thingy:
revert

**Comment by theofficialgman** [comment]
> > @Botspot you forgot about squash and merge didn’t you?.... 35 more ugly commits in the history now
> 
> Oh no, not again! lol. Is there a way to undo commits?

no, not unless you force push
whatever you do DO NOT HIT REVERT
that just adds more commits to remove the changes

**Comment by theofficialgman** [comment]
@Botspot its fine, its not going to hurt anything
just leave it
you don't want to ever force push otherwise git pulls can fail if users have cloned the repo

**Comment by Botspot** [comment]
This app is leaving behind files after uninstallation. See this issue: https://github.com/AntiMicroX/antimicrox/issues/68

**Comment by Botspot** [comment]
Modifying the `install` script to *not* remove the ~/antimicrox allowed me to run `sudo make uninstall` in that folder. I used the output to revise the uninstall script in commit https://github.com/Botspot/pi-apps/commit/efdc7e87f34519d379a14ddb371c3985dc3eafa3.

**Comment by ryanfortner** [comment]
@Botspot couldn't we just use debs for simpler installation/uninstallation? https://github.com/Botspot/pi-apps/pull/1220

**Comment by Botspot** [comment]
> @Botspot couldn't we just use debs for simpler installation/uninstallation? #1220

We might as well. Merged.

**Pull request merged**
