### PR TITLE
remove pi-apps.io from readme

### PR DESCRIPTION
**Pull request by theofficialgman**
@ryanfortner implemented a cryptominer on March 6th on pi-apps.io and has been making money off of our users

de-promote pi-apps.io due to this practice

### CODE REVIEW

**Comment by ryanfortner** [comment]
The website uses a monetization technique using Duinotize (https://github.com/mobilegmYT/Duinotize) as an alternative to ads. 

Even though I implemented this in the website’s code, I have not made even half a cent. It’s just an experiment and I am 100% ok with removing it.

**Comment by ryanfortner** [comment]
I would appreciate if you could consider reverting these changes. I’ve removed the miner.

**Comment by Crilum** [comment]
@theofficialgman I can confirm this:
image

@ryanfortner You still need to remove the `<script>` tag:
image

image

**Comment by theofficialgman** [comment]
I'll wait for @Botspot to comment... its his repo after all.

**Comment by ryanfortner** [comment]
I just removed the remaining `<script>` tags.

> Just saying, even half a cent is a lot of Duinocoins...

yeah they are not worth much and are also not exchangeable for actual money. I earned just under 20 duco with the miner implemented.

**Comment by Crilum** [comment]
>not exchangeable for actual money.

You can [exchange](https://exchange.duinocoin.com/) Duinocoin for other cryptocurrencies, that you can exchange to USD.. But that doesn't really matter.

**Comment by Botspot** [comment]
This is a serious matter and I will need some time to decide how to respond to it.

**Comment by progamer562** [comment]
im confused about this what are you talking about

**Comment by Crilum** [comment]
> im confused about this what are you talking about

@ryanfortner had implemented a cryptominer on the pi-apps.io website, using user's computers to mine crypto for himself without even a popup, or any information for the user (unless they looked in Dev Tools.. Which most people don't.) or telling @Botspot what he was doing.

@ryanfortner If I got anything wrong, please tell me. I'm not trying to offend you. :)

**Pull request merged**
