### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by CoderLogy**

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
We will wait for @Botspot for this one.

**Comment by CoderLogy** [comment]
ok

**Comment by CoderLogy** [comment]
@Botspot  I am waiting

**Comment by Botspot** [comment]
Closing this pull request as it's a duplicate of #823.

**Comment by CoderLogy** [comment]
So add the code of conduct @Botspot

**Pull request closed without merging**
