### PR TITLE
Use ASCII version of `Pi-Apps` text in `generate_logo`

### PR DESCRIPTION
**Pull request by cycool29**
Result:

### CODE REVIEW

**Comment by Botspot** [comment]
I personally find outline-based text harder to read. Perhaps it would be okay if the text was filled in, though that would require a few more hours spent on https://unicode-search.net.

**Comment by open-sorcerer64** [comment]
> How about this?
> 
> image

That looks amazing imo

**Comment by Botspot** [comment]
How about this?
2022-01-10-214515_1920x1080_scrot

**Comment by Crilum** [comment]
@Botspot I love it!

**Comment by Crilum** [comment]
> > Perhaps it would be okay if the text was filled in, though that would require a few more hours spent on https://unicode-search.net.
> 
> Well that's what I ended up doing.
> 
> How is it? 2022-01-10-214515_1920x1080_scrot

Looks way cooler than this:
image

**Comment by cycool29** [comment]
> Well that's what I ended up doing.
> 
> How is it? 2022-01-10-214515_1920x1080_scrot

Cool!

**Pull request merged**
