### PR TITLE
Tor Browser Fix

### PR DESCRIPTION
**Pull request by SebTNT**
Update to Tor Browser on Sourceforge.

### CODE REVIEW

**Comment by SebTNT** [comment]
@Botspot Its been tested, can it be merged?

**Comment by theofficialgman** [comment]
We have an auto updater, sorry this is incompatible with it

**Comment by SebTNT** [comment]
May I ask why it does not work?

**Comment by SebTNT** [comment]
i see how it works and am writing a fix that should work.

**Pull request closed without merging**
