### PR TITLE
Add support for alternate package names

### PR DESCRIPTION
**Pull request by Jai-JAP**
Add support for alternate package names if primary package name is not available in repos.
 
 Box86 install-64 currently looks like
 
 ```
 #install box86 dependencies
 CODENAME="$(lsb_release -cs)"
 if [[ "${CODENAME}" == "focal" || "${CODENAME}" == "buster" ]]; then
 "${DIRECTORY}/pkg-install" "libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf libc6:armhf libx11-6:armhf libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.2:armhf libpng16-16:armhf libcal3d12v5:armhf libsdl2-net-2.0-0:armhf libopenal1:armhf libsdl2-image-2.0-0:armhf libvorbis-dev:armhf libcurl4:armhf osspd:armhf pulseaudio:armhf libjpeg62:armhf libudev1:armhf libgl1-mesa-dev:armhf libsnappy1v5:armhf libx11-dev:armhf libsmpeg0:armhf libboost-filesystem1.67.0:armhf libboost-program-options1.67.0:armhf libavcodec58:armhf libavformat58:armhf libswscale5:armhf libmyguiengine3debian1v5:armhf libboost-iostreams1.67.0:armhf  libsdl2-mixer-2.0-0:armhf" "$(dirname "$0")" || exit 1
 elif [[ "${CODENAME}" == "groovy" || "${CODENAME} == "hirsute" ]]; then
 "${DIRECTORY}/pkg-install" "libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf libc6:armhf libx11-6:armhf libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.2:armhf libpng16-16:armhf libcal3d12v5:armhf libsdl2-net-2.0-0:armhf libopenal1:armhf libsdl2-image-2.0-0:armhf libvorbis-dev:armhf libcurl4:armhf osspd:armhf pulseaudio:armhf libjpeg62:armhf libudev1:armhf libgl1-mesa-dev:armhf libsnappy1v5:armhf libx11-dev:armhf libsmpeg0:armhf libboost-filesystem1.71.0:armhf libboost-program-options1.71.0:armhf libavcodec58:armhf libavformat58:armhf libswscale5:armhf libmyguiengine3debian1v5:armhf libboost-iostreams1.71.0:armhf  libsdl2-mixer-2.0-0:armhf" "$(dirname "$0")" || exit 1
 ```
 
 Afterwards it can be reduced to look like
 
 ```
 #install box86 dependencies
 "${DIRECTORY}/pkg-install" "libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf libc6:armhf libx11-6:armhf libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.2:armhf libpng16-16:armhf libcal3d12v5:armhf libsdl2-net-2.0-0:armhf libopenal1:armhf libsdl2-image-2.0-0:armhf libvorbis-dev:armhf libcurl4:armhf osspd:armhf pulseaudio:armhf libjpeg62:armhf libudev1:armhf libgl1-mesa-dev:armhf libsnappy1v5:armhf libx11-dev:armhf libsmpeg0:armhf libboost-filesystem1.67.0:armhf | libboost-filesystem1.71.0:armhf libboost-program-options1.67.0:armhf | libboost-program-options1.71.0:armhf libavcodec58:armhf libavformat58:armhf libswscale5:armhf libmyguiengine3debian1v5:armhf libboost-iostreams1.67.0:armhf | libboost-iostreams1.71.0:armhf  libsdl2-mixer-2.0-0:armhf" "$(dirname "$0")" || exit 1
 ```
 
 So that apt will automatically choose which package to install among the alternatives separated with " | "
 
 This is required as it can be used to reduce scripts as some packages have different names in Debian(Raspbian) and Ubuntu and one among them I recently came across is libturbojpeg [in Debian](https://packages.debian.org/search?keywords=libturbojpeg) and [in Ubuntu](https://packages.ubuntu.com/search?keywords=libturbojpeg)
 
 Also some packages have different names different distros as in the above example

### CODE REVIEW

**Comment by Botspot** [comment]
Interesting. I wasn't aware deb files supported stuff like this.

Has this been tested? (It seems too simple a modification, and wouldn't [the failsafe](https://github.com/Botspot/pi-apps/pull/669/files#diff-5e6f7edaa49f461ac2ce55d9a3a728f6c2546f4044bd58f1888994e661368fc2R179) mess stuff up?)

**Comment by Jai-JAP** [comment]
Yes this is tested and works fine with the modification in the Box86 install-64 i mentiomed earlier in this pull

**Comment by Jai-JAP** [comment]
> Interesting. I wasn't aware deb files supported logic like this.

I too came accross this recently when I reviewed the control file of Wine i386 packages
```
Package: wine-stable
Source: wine
Version: 6.0.0~buster-1
Architecture: i386
Maintainer: Rosanne DiMesio <dimesio@earthlink.net>, Marcus Meissner <meissner@suse.com>
Installed-Size: 12243
Pre-Depends: dpkg (>= 1.14.12ubuntu3)
Depends: debconf (>= 0.5) | debconf-2.0, libc6 (>= 2.28), wine-stable-i386 (= 6.0.0~buster-1)
Section: otherosfs
Priority: optional
Multi-Arch: foreign
Description: WINE Is Not An Emulator - runs MS Windows programs
 Wine is a program which allows running Microsoft Windows programs
 (including DOS, Windows 3.x and Win32 executables) on Unix. It
 consists of a program loader which loads and executes a Microsoft
 Windows binary, and a library (called Winelib) that implements Windows
 API calls using their Unix or X11 equivalents.  The library may also
 be used for porting Win32 code into native Unix executables.
Original-Maintainer: WineHQ Builds <webmaster@fds-team.de>
```

```
 Package: wine-stable-i386
 Source: wine
 Version: 6.0.0~buster-1
 Architecture: i386
 Maintainer: Rosanne DiMesio <dimesio@earthlink.net>, Marcus Meissner <meissner@suse.com>
 Installed-Size: 486825
 Pre-Depends: dpkg (>= 1.14.12ubuntu3)
 Depends: libasound2 (>= 1.0.16), libc6 (>= 2.28), libfaudio0 (>= 19.06.07), libglib2.0-0 (>= 2.12.0), libgphoto2-6 (>= 2.5.10), libgphoto2-port12 (>= 2.5.10), libgstreamer-plugins-base1.0-0 (>= 1.0.0), libgstreamer1.0-0 (>= 1.4.0), liblcms2-2 (>= 2.2+git20110628), libldap-2.4-2 (>= 2.4.7), libmpg123-0 (>= 1.13.7), libopenal1 (>= 1.14), libpcap0.8 (>= 0.9.8), libpulse0 (>= 0.99.1), libudev1 (>= 183), libvkd3d1 (>= 1.0), libx11-6, libxext6, libxml2 (>= 2.9.0), ocl-icd-libopencl1 | libopencl1, libasound2-plugins, libncurses6 | libncurses5 | libncurses
 Recommends: libcapi20-3, libcups2, libdbus-1-3, libfontconfig1, libfreetype6, libglu1-mesa | libglu1, libgnutls30 | libgnutls28 | libgnutls26, libgsm1, libgssapi-krb5-2, libjpeg62-turbo | libjpeg8, libkrb5-3, libodbc1, libosmesa6, libpng16-16 | libpng12-0, libsane | libsane1, libsdl2-2.0-0, libtiff5, libv4l-0, libxcomposite1, libxcursor1, libxfixes3, libxi6, libxinerama1, libxrandr2, libxrender1, libxslt1.1, libxxf86vm1
 Section: otherosfs
 Priority: optional
 Multi-Arch: foreign
 Description: WINE Is Not An Emulator - runs MS Windows programs
  Wine is a program which allows running Microsoft Windows programs
  (including DOS, Windows 3.x and Win32 executables) on Unix.
  .
  This package contains the files needed to support 32-bit Windows
  programs.
 Original-Maintainer: WineHQ Builds <webmaster@fds-team.de>
```

**Comment by Jai-JAP** [comment]
@Botspot

**Comment by Jai-JAP** [comment]
@Botspot ^

**Comment by Botspot** [comment]
Merging this because the failsafe was removed a while back from pkg-install.

**Pull request merged**
