### PR TITLE
Added AbiWord

### PR DESCRIPTION
**Pull request by open-sorcerer64**
Just added AbiWord

### CODE REVIEW

**Comment by open-sorcerer64** [comment]
Anyone up?

**Comment by open-sorcerer64** [comment]
Hey??

**Comment by Botspot** [comment]
I haven't been online yet until just now, so please relax.

Suggestions:

- Compare this app to similar ones, like LibreOffice Writer and WPS Office. Explain when someone would prefer to use this app more than other alternatives in Pi-Apps.
- Add a "to run in a terminal" line in the description.

**Comment by open-sorcerer64** [comment]
> I haven't been online yet until just now, so please relax.
Ok, Nevermind 

> Suggestions:
> 
> * Compare this app to similar ones, like LibreOffice Writer and WPS Office. Explain when someone would prefer to use this app more than other alternatives in Pi-Apps.
Having alternatives is good, right?

> * Add a "to run in a terminal" line in the description.

Kk, on it

**Comment by open-sorcerer64** [comment]
Do you mind if I close this and start another PR? Actually I messed up my fork

**Comment by Botspot** [comment]
> Do you mind if I close this and start another PR? Actually I messed up my fork

That's fine.

**Pull request closed without merging**
