### PR TITLE
better implementation of getting `screen_width` and `screen_height` in `updater` script

### PR DESCRIPTION
**Pull request by touhidurrr**
this is a better and more universal implementation

### CODE REVIEW

**Comment by theofficialgman** [comment]
can confirm, this should work nicely

**Comment by Botspot** [comment]
I will change the implementation in the `gui` script to match this.

**Comment by touhidurrr** [comment]
@Botspot @theofficialgman wanted you guys to look at this post.
https://unix.stackexchange.com/a/683902/383916
Someone is saying that it is not **POSIX** Complient.

**Comment by theofficialgman** [comment]
I don't think POSIX compliance has ever been a concern for Pi-Apps. The reason Bash is used over Sh is so we get those non-POSIX compliant command structures (example: arrays are not POSIX compliant and are not included in Sh as a result).

**Comment by touhidurrr** [comment]
> I don't think POSIX compliance has ever been a concern for Pi-Apps. The reason Bash is used over Sh is so we get those non-POSIX compliant command structures (example: arrays are not POSIX compliant and are not included in Sh as a result).

Makes sense. But I still wanted to show you guys the thread for documentation reasons and future troubleshooting.

**Comment by Botspot** [comment]
> > I don't think POSIX compliance has ever been a concern for Pi-Apps. The reason Bash is used over Sh is so we get those non-POSIX compliant command structures (example: arrays are not POSIX compliant and are not included in Sh as a result).
> 
> Makes sense. But I still wanted to show you guys the thread for documentation reasons and future troubleshooting.

Thank you. I was curious about how that regex was working.

**Pull request merged**
