### PR TITLE
Changes to README.md - Privacy - Piping to Bash and Analytics 

### PR DESCRIPTION
**Pull request by CleanMachine1**
I personally feel its wrong to pipe code straight to bash, therefore I have added a statement about it, and given more of a reason to use the manual installation, my reasoning for this

Also fixed the word Autostarted as it should be auto-started 

Small commit, but still a useful one

### CODE REVIEW

**Comment by CleanMachine1** [comment]
The privacy noticed was also added as I feel everyone should have easy clear information for privacy

It shouldn't be hidden in the settings menu

**Comment by CleanMachine1** [comment]
Installation didn't have a cap I

**Comment by Botspot** [comment]
One can't argue against the convenience of using a single-command installation script.

While it can be controversial, it was necessary to add a one-liner. Before that, people were git cloning to the wrong folder, or trying to download the zip from the github website. Many people made mistakes during installation, but since adding the one-line installation command, the number of successful installs has increased, while the number of people experiencing issues has decreased to nearly zero.

Those who don't trust piping to bash, are almost always going to be Linux-savvy. Those people are the minority of users, and we kept them happy by providing manual installation instructions.

Providing a warning will only serve to confuse the noob users, while at the same time it will appear contradictory: "Why does the official Pi-Apps readme warn users against using its own installation script?"

**Comment by CleanMachine1** [comment]
Regardless, it should be mentioned, safety shouldn't be hidden, it may stop someone piping a malicious script in the future!

**Comment by CleanMachine1** [comment]
> Those who don't trust piping to bash, are almost always going to be Linux-savvy. Those people are the minority of users, and we kept them happy by providing manual installation instructions.

**Comment by CleanMachine1** [comment]
> Those who don't trust piping to bash, are almost always going to be Linux-savvy. Those people are the minority of users, and we kept them happy by providing manual installation instructions.

No.
Why shouldn't people learn.

Also most Linux users (I expect) are fluent with things but may not see the issue with aspects

**Comment by Botspot** [comment]
> Providing a warning will only serve to confuse the noob users, while at the same time it will appear contradictory: "Why does the official Pi-Apps readme warn users against using its own installation script?"

Plenty of other repos reach a compromise by including both a manual installation script, and a simpler one-liner option.  
Those repos simply allow the user to choose: those who distrust can install manually, while those who want to install it quickly and effortlessly can use the one-liner.

So far so good.

But what you're asking to do, is to educate users _against_ using one of the options. To say it's unsafe or whatever. For Pi-Apps to cast a doubt on itself as if it may contain malware. Such a move would not benefit anybody.

Instead, what do you think about something like this?  
2021-04-04-145455_1920x1080_scrot
I'd also like @Itai-Nelken's input on this.

**Comment by CleanMachine1** [comment]
And what about the other edit I have made about analytics

**Comment by CleanMachine1** [comment]
> But what you're asking to do, is to educate users against using one of the options. To say it's unsafe or whatever. For Pi-Apps to cast a doubt on itself as if it may contain malware. Such a move would not benefit anybody.

No, there needs to be a need to teach people to read code before just running it, if everyone never looked at it because they used the easy 1-liner, things can slip through
But what you're asking to do, is to educate users against using one of the options. To say it's unsafe or whatever. For Pi-Apps to cast a doubt on itself as if it may contain malware. Such a move would not benefit anybody.

People shouldn't feel that pi-apps has malware because its acknowledged that piping is controversial, its for the greater good overall.

**Comment by CleanMachine1** [comment]
About the edit made in that picture

It shouldn't be confusing, it should be something like "What this line does"

**Comment by CleanMachine1** [comment]
Also I am not saying remove it, rather tell people its not good practise

**Comment by Botspot** [comment]
> Also I am not saying remove it, rather tell people its not good practise

Other repos don't do that. Why should this one?

> (about the picture)
> instead of confusing people with long words

I think you misunderstood the picture. I'm thinking of changing "Manual installation" with "Feel free to inspect the codebase first by installing Pi-Apps manually: (click here)".  
What do you think of that?

**Comment by CleanMachine1** [comment]
I feel thats worse than the original.
It should be simple just to make it look nice 

Maybe have another summary between the simple and manual just called "Piping to Bash", then have what I have done in my initial commit

In fact I will commit that change now
Give me 5

**Comment by CleanMachine1** [comment]
@Botspot Done.

Have you seen the notice about the analytics part. To be honest I thought that would be the thing to raise controversy

**Comment by Botspot** [comment]
> @Botspot Done.
> 
> Have you seen the notice about the analytics part. To be honest I thought that would be the thing to raise controversy

Yes I have. One thing at a time though please.

**Comment by CleanMachine1** [comment]
Are you satisfied with https://github.com/Botspot/pi-apps/pull/533/commits/6c197f671c2791d3936d627ffa0b337587b279e2 ?

**Comment by Botspot** [comment]
There, I changed it to the way I wanted.

I do agree with you that mentioning the analytics on the readme is a good idea. But, any day now, Pi-Apps will publicly display analytics data within the app list. And then at that point it would be apparent and obvious that Pi-Apps keeps tallys of everything so I'd see little need to mention it in the readme too. So right now it would be fine to mention analytics, but in a few days it wouldn't be necessary because it would be obvious.

I'll merge the changes.

**Comment by CleanMachine1** [comment]
Small error made, if you click on the manual installation, it doesn't go into code tags

**Comment by Botspot** [comment]
> Small error made, if you click on the manual installation, it doesn't go into code tags

There, fixed it. 28763fc9e62de7b9a421b5432e18b0eeb7c8f0a7

**Comment by Botspot** [comment]
> I do agree with you that mentioning the analytics on the readme is a good idea. But, any day now, Pi-Apps will publicly display analytics data within the app list.

Done. Pi-Apps now displays the number of users per app with commit 6f8dad5dafd4027b04c5a078f9e993a1ec4cb244.

**Pull request merged**
