### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by KOSASIH**

### CODE REVIEW

**Comment by Botspot** [comment]
Hello @KOSASIH, I am not sure how familiar you are with pi-apps as a project structure.
In all likelihood, if there is ever a security incident involving pi-apps, the problem will be due to a vulnerability found in one of the apps. In nearly all cases, Pi-Apps will download the necessary app files straight from the original project developers. If an issue arises, the problem should be reported to the devs of that app, and once it is fixed then all our users will receive the fix in the form of an ordinary app update.

Have you thought through these types of scenarios, and would you be willing to take some thought to tailor a potential SECURITY.md to better fit the pi-apps project structure? For one minor example of why a standard SECURITY.md file would be a poor fit here: pi-apps does have any version numbers, meaning the entire section on which versions are 'supported', does not apply here.

**Comment by theofficialgman** [comment]
@Botspot same user as last time https://github.com/Botspot/pi-apps/pull/2429

It is likely an annoying bot they have running that automatically generates this crap.

**Comment by Botspot** [comment]
Bot must be getting good to react to my reply with a 👍.
I'm sure that @KOSASIH will reply here if not a bot. ;)

**Comment by KOSASIH** [comment]
I'm not Bot..  ☺  i'm contributor of your project...

KOSASIH

Pada tanggal Sen, 5 Feb 2024 03.42, Botspot ***@***.***>
menulis:

**Comment by Botspot** [comment]
> I'm not Bot.. ☺ i'm contributor of your project... KOSASIH

Well then, @KOSASIH, please respond to my comment given earlier, which you can refer back to using [this link.](https://github.com/Botspot/pi-apps/pull/2545#issuecomment-1925603648)

**Comment by theofficialgman** [comment]
@Botspot don't bother. The user @KOSASIH has been spam opening PRs like this for many months now. I see that they have opened many for repositories for the github user https://github.com/pi-apps , which is why they have mistakenly called themselves "a contributor of our project". We have no affiliation with the Pi Network.

**Comment by KOSASIH** [comment]
I see open flaws in your system, so I suggest completing a security system. I have cloned your repo and added many files to complete it as a form of my contribution to your project. This is based on the idea that it can help improve your project. 

Thank you.

**Comment by Botspot** [comment]
> @Botspot I see open flaws in your system, so I suggest completing a security system. I have cloned your repo and added many files to complete it as a form of my contribution to your project. This is based on the idea that it can help improve your project.
> 
> Thank you.

All your commits as seen [here](https://github.com/Botspot/pi-apps/compare/master...KOSASIH:pi-apps:master) are low-quality and demonstrate zero understanding with how our project works.
@KOSASIH, you have been banned from all Botspot repositories and you are not welcome to contact us any more.

**Pull request closed without merging**
