### PR TITLE
Add settings icon

### LINKED ISSUE #1206: Change Pi-Apps Settings icon
### Cool ideas?

I would like to put the Pi-Apps Settings shortcut on my Launch Bar, but the icon is the same as Pi-Apps, so I won't be able to tell them apart. Could we change the Pi-Apps Settings icon to have, like, a gear in it or something?

### PR DESCRIPTION
**Pull request by cycool29**
To close #1206.

### CODE REVIEW

**Comment by Crilum** [comment]
I think we need to change the Desktop Entry, I had to change mine manually..

**Comment by cycool29** [comment]
> I think we need to change the Desktop Entry, I had to change mine manually..

I have changed that in `install` script.
Maybe we can add a `runonce` to change that for existing installs.

**Comment by Crilum** [comment]
Yeah, cause the new icon isn't going to show up on the Shortcut unless everybody reinstalls Pi-Apps...

**Comment by cycool29** [comment]
https://github.com/Botspot/pi-apps/pull/1301

**Pull request merged**
