### PR TITLE
Force mcpi reinstall and add some notes

### PR DESCRIPTION
**Pull request by mobilegmYT**
DO NOT MERGE NOW I ACCIDENTLY CLICKED WRONG BUTTON MAKING PR. Merge when gmcpil 1.13.1 is released.

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
mark as 'ready for review' when gmcpil 1.13.1 is released.

**Comment by mobilegmYT** [comment]
@Itai-Nelken ready for merge

**Comment by Botspot** [comment]
Why are we letting the user know that the above "errors" are normal, when these errors have been completely silenced with `&>/dev/null`?

**Comment by mobilegmYT** [comment]
> Why are we letting the user know that the above "errors" are normal, when these errors have been completely silenced with `&>/dev/null`?

I think the /dev/null stuff is broken, if you look at pi-apps error logs you'll see that the errors still show up for packages not found.

**Comment by Botspot** [comment]
Is this PR still relevant?

**Comment by mobilegmYT** [comment]
> Is this PR still relevant?

Er no, I was hoping to switch it to use the custom buster debs and add sound support, but since it didn't work for you (segfault) I'm keeping it at the current version without sound.

**Pull request closed without merging**
