### PR TITLE
Make DDNet compile on Debian Buster

### PR DESCRIPTION
**Pull request by Rak1ta**
After contacting the [ddnet](https://github.com/ddnet/ddnet/issues/6145) repo, the package was changed to build the game.
There is also a warning in the [README](https://github.com/ddnet/ddnet/commit/747dc1b0ce514c31b78ead0371bf8bb2f606c5f9), but I don't know if it should be added. I have everything working.

### CODE REVIEW

**Comment by Botspot** [comment]
The main problem I see with this is that you can only have either rustc or rustc-mozilla installed.
Trying to install both results in this error:
```
$ sudo apt install rustc rustc-mozilla
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rustc-mozilla : Conflicts: rustc
                 Recommends: cargo (>= 0.60.0~~)
E: Unable to correct problems, you have held broken packages.
```
For all systems with rustc as a dependency for something else, this update to DDNet will break installation, including on systems where DDNet previously worked fine.

**Comment by Rak1ta** [comment]
@Botspot Is it possible to make rustc-mozilla install only if rustc is not installed and only on Buster?  If these conditions are not met issue a warning. I have almost all programs installed with pi-apps, no problem.

**Comment by Botspot** [comment]
> @Botspot Is it possible to make rustc-mozilla install only if rustc is not installed and only on Buster? If these conditions are not met issue a warning. Make rustc a priority during installation.

Yes, this is possible.

> Unfortunately, I don't understand this. I hope for you. I have almost all programs installed with pi-apps, no problem.

I think you are saying that you don't know how to do this yourself. That is fine. I will work on it, and I encourage you to understand what I have done, asking questions as necessary.

**Comment by Botspot** [comment]
OK, I have made initial (untested) changes.
I am testing it on my Bullseye system now.

@Rak1ta , please test this on your system as well.
I want to make sure that it behaves as expected when:

- A too old version of rustc is already installed
- rustc is not installed

To test this easily: Go to pi-apps settings, click Import App, and type in 2200. (the number of this Pull Request)

**Comment by Rak1ta** [comment]
@Botspot 
```
tail: warning: --retry only effective for the initial open
Installing DDNet...

User error: DDNet cannot install because your operating system has too old of a version of Rust installed. You can try removing the rustc package, then installing DDNet again.
```
```
tail: warning: --retry only effective for the initial open
Installing DDNet...

Will install these packages: build-essential cargo cmake git libcurl4-openssl-dev libssl-dev libfreetype6-dev libglew-dev libnotify-dev libogg-dev libopus-dev libopusfile-dev libpnglite-dev libsdl2-dev libsqlite3-dev libwavpack-dev python3 google-mock libx264-dev libavfilter-dev libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev rustc-mozilla 
Creating an empty apt-package to install the necessary apt packages...
```

**Comment by Rak1ta** [comment]
@Botspot And if rustc is old and rustc-mozilla doesn't exist, is it possible to issue a warning about it?

**Comment by Botspot** [comment]
Your test results appear to be correct.

In terms of how I made this work, I simply used some functions from Pi-Apps' list of useful helper functions.
We have had situations before when a package needs to be newer than a certain version number, so I made the `package_is_new_enough` function for that purpose.
See: https://github.com/Botspot/pi-apps/blob/master/DOCUMENTATION.md#the-api-script

**Comment by Botspot** [comment]
@Rak1ta, what version of the rustc and rustc-mozilla packages are available on your distro?

Run a command like this to find out:
```
~/pi-apps/api package_latest_version rustc
```

**Comment by Rak1ta** [comment]
@Botspot I'm talking about it - https://github.com/ddnet/ddnet/pull/6146#issuecomment-1354968456
```
pi@raspberrypi:~ $ ~/pi-apps/api package_latest_version rustc
1.41.1+dfsg1-1~deb10u1+rpi1
```

**Comment by Botspot** [comment]
Now the script verifies that rustc-mozilla is available and is new enough. I've also reworked some of the if statements to avoid repeatedly checking if rustc is too old. If it is new enough, the first conditional will take priority.

**Comment by Botspot** [comment]
Before merging, I would like to get confirmation from @theofficialgman that these changes do not cause any unintended consequences on his older Ubuntu system.

**Comment by theofficialgman** [comment]
oh oops, see my comments in the discord

my plan was to add the ubuntu ppa for firefox bionic onto debian buster (like the firefox rapid release app)
https://github.com/Botspot/pi-apps/blob/master/apps/Firefox%20Rapid%20Release/install

this repo always has the stable release of rustc and cargo

using rustc-mozilla as a solution like this PR uses is not great because even it is out of date and not updated frequently

**Comment by theofficialgman** [comment]
actually probably just will use the ppa that that one depends on:
https://launchpad.net/~ubuntu-mozilla-security/+archive/ubuntu/rust-next?field.series_filter=bionic

**Comment by Botspot** [comment]
This seems like a much more solid solution, @theofficialgman. Do you plan to take it from here?

**Comment by theofficialgman** [comment]
> This seems like a much more solid solution, @theofficialgman. Do you plan to take it from here?

yup I got it
since I have a pi3 now, just verifying myself on buster before I push changes

**Comment by theofficialgman** [comment]
closed with https://github.com/Botspot/pi-apps/commit/f5d65227294c9d41931252296e7aa03671073559

**Pull request closed without merging**
