### PR TITLE
add obs-studio bullseye support

### PR DESCRIPTION
**Pull request by ryanfortner**
for #1592

### CODE REVIEW

**Comment by theofficialgman** [comment]
I don't expect this deb to also work on buster. I'm fine with having a unique deb per version and can add that to the install script once they are tested

**Comment by ryanfortner** [comment]
Unfortunately I've lost the buster arm64 deb while adding the bullseye one to my repo, so I'll have to compile that from scratch again. In the meantime, can this pr be merged since the old link is no longer valid?

**Comment by theofficialgman** [comment]
no I won't do that, since that would update all installed users to a broken version if they are on buster
you forget about your mirrors, sourceforge isn't syncing so its perfect and I grabbed the lost releases
here is a zip containing the armhf and arm64 releases
[obs-studio_27.2.0-backup.zip](https://github.com/Botspot/pi-apps/files/8238838/obs-studio_27.2.0-backup.zip)

**Comment by ryanfortner** [comment]
Whoops, I forgot about the mirrors :laughing: thanks for reminding me

I've added back the old debs now

**Comment by ryanfortner** [comment]
@theofficialgman I made some changes to `install-64`, could you please take a look?

**Comment by theofficialgman** [comment]
> @theofficialgman I made some changes to `install-64`, could you please take a look?

can you un-do the hack which was done here locally on your install and see if it still works now that we have bullseye specific debs?
```
#temporary fix of `error while loading shared libraries: libxcb-util.so.0: cannot open shared object file: No such file or directory`
if ! package_installed libxcb-util0 ;then
  libpath="$(dirname "$(dpkg -S libxcb-util.so.1 | grep "libxcb-util.so.1$" | awk '{print $2}')")" #Value on RPiOS Bullseye: /usr/lib/arm-linux-gnueabihf
  if [ ! -e "${libpath}/libxcb-util.so.0" ] ;then
    status "Fixing libxcb-util.so.0 library"
    sudo ln -sf "${libpath}/libxcb-util.so.1" "${libpath}/libxcb-util.so.0"
  fi
fi
```
`libxcb-util.so.0` is what is supposed to not exist in bullseye but the hack "adds it back" just remove it and see if obs still launches

**Comment by ryanfortner** [comment]
@theofficialgman everything good so far?

**Comment by theofficialgman** [comment]
closed with https://github.com/Botspot/pi-apps/commit/0112d125eea852cfe751034cbbe48050f4ca3cca

**Pull request closed without merging**
