### PR TITLE
Update MCPI-Reborn (once again)

### PR DESCRIPTION
**Pull request by mobilegmYT**
I've tested build #24 and tbr fixed the GLSW launch issues. Feel free to test and install the latest build from his jenkins before merging.

### CODE REVIEW

**Comment by Botspot** [comment]
Works for me.

**Comment by mobilegmYT** [comment]
@Botspot Strange thing, I upgraed and it said it updated everything, but I didn't see it reinstall MCPI even though it was installed in pi-apps.

**Comment by Botspot** [comment]
> @Botspot Strange thing, I upgraed and it said it updated everything, but I didn't see it reinstall MCPI even though it was installed in pi-apps.

Make a random change to your local install script. Run the updater again. It should uninstall and reinstall.

**Comment by mobilegmYT** [comment]
> > @Botspot Strange thing, I upgraed and it said it updated everything, but I didn't see it reinstall MCPI even though it was installed in pi-apps.
> 
> Make a random change to your local install script. Run the updater again. It should uninstall and reinstall.

Strange, it didn't reinstall even after changing the install script. Just said in green text "updated Minecraft pi" or whatever.

**Comment by Botspot** [comment]
> Strange, it didn't reinstall even after changing the install script. Just said in green text "updated Minecraft pi" or whatever.

I'm looking into it.

**Comment by Botspot** [comment]
Just found the problem. Duh.  
So the update procedure for all apps has been broken for a few weeks, maybe a month it looks like.

**Comment by mobilegmYT** [comment]
> Just found the problem. Duh.
> So the update procedure for all apps has been broken for a few weeks, maybe a month it looks like.

No wonder none of my apps had been updating 😆

**Comment by Botspot** [comment]
I wonder how many apps this has broken and we don't even know!

**Comment by Botspot** [comment]
Okay. Fixed with commit be143e2934e3f073cf02727e2d45e2ca6f57bce0.

The good news is that when I accidentally merged your PR when I shouldn't have, it really didn't do anything at all, because of this updating bug.

**Comment by mobilegmYT** [comment]
Cool! Now you'll need to read the changelog and update all the install scripts so they properly update 😆

**Comment by Botspot** [comment]
> Cool! Now you'll need to read the changelog and update all the install scripts so they properly update

And what about all the people who installed stuff afterwards? I may update a few scripts that were changed recently, but stuff older than a week I think is simply too late.

**Pull request merged**
