### PR TITLE
Update Etcher to v1.5.120

### PR DESCRIPTION
**Pull request by chunky-milk**
also note that the deb name is now `balena-etcher` and not `balena-etcher-electron`.

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
Could you make the uninstall script something like this please (checks if the old etcher package is installed, if yes uninstall it else uninstall the new one). **This is not tested**
```bash
if dpkg -l "balena-etcher-electron" &> /dev/null ;then
	sudo apt purge -y balena-etcher-electron
else
	sudo apt purge -y balena-etcher
fi
```

**Comment by Itai-Nelken** [comment]
# not ready for merging yet! the new etcher builds seem to be broken!

**Comment by chunky-milk** [comment]
Should I close this for now?

**Comment by Itai-Nelken** [comment]
If you want

**Pull request closed without merging**
