### PR TITLE
Update MC Bedrock to 683

### PR DESCRIPTION
**Pull request by mobilegmYT**

### CODE REVIEW

**Comment by Botspot** [comment]
Would anyone be interested in adding a Github Actions script to automatically keep this app updated from now on?

**Comment by theofficialgman** [comment]
> Would anyone be interested in adding a Github Actions script to automatically keep this app updated from now on?

this repo is under flux right now. ChristopherHX is no longer maintaining the fork and mrarm has come back.
the repo is being majorly restructured. for now, this script should stay manual

**Comment by theofficialgman** [comment]
also, the launcher has builtin automatic updates, no updates from pi-apps are necessary

**Comment by mobilegmYT** [comment]
> also, the launcher has builtin automatic updates, no updates from pi-apps are necessary Screenshot from 2022-02-08 16-24-15 clicking the button there downloads the new version and sets it up automatically

It doesn't seem to work for me, it doesn't do anything. In previous versions it also gave me a error saying something wasn't found.

**Comment by theofficialgman** [comment]
> It doesn't seem to work for me, it doesn't do anything. In previous versions it also gave me a error saying something wasn't found.

I wonder if pi-apps breaks this auto-updating functionality... you make sure to re-start the appimage after it updated right?
I always installed the appimage and didn't rename it, while pi-apps renames the appimage to `MCBedrock.Appimage`

**Comment by theofficialgman** [comment]
@mobilegmYT just tested with pi-apps installation and had no issues with the auto updating
You must have forgotten to restart the appimage, or maybe you are using `TheAssassin/AppImageLauncher` and are actually not running the correct .desktop file

**Comment by theofficialgman** [comment]
oh wait no... I see the problem @Botspot you can't move the appimage to /opt because you need sudo to write to that directory
that breaks auto updating

**Pull request closed without merging**
