### PR TITLE
Change desktop file to show a tiny fps counter

### PR DESCRIPTION
**Pull request by mobilegmYT**
image

### CODE REVIEW

**Comment by Botspot** [comment]
Very nice.
Could we do the same for MC Java by any chance?

**Comment by mobilegmYT** [comment]
You actually can, but you need Optfine mod installed. I can do some doodads to ask if the user wants it installed.

**Comment by mobilegmYT** [comment]
Hmm. The desktop argument doesn't seem to work.

**Comment by Botspot** [comment]
Try this:
`bash -c "Exec=GALLIUM_HUD=simple,fps /usr/bin/MCBedrock.AppImage"`

**Comment by Botspot** [comment]
Merged with #29

**Pull request merged**
