### PR TITLE
Added GTA 3 & GTA VC

### PR DESCRIPTION
**Pull request by Jai-JAP**
This commit needs to be tested.
The zip file for the GTA Apps for testing is below. Extract it to ~/pi-apps/ to get GTA 3 and GTA VC
[GTA.zip](https://github.com/Botspot/pi-apps/files/7175174/GTA.zip)

 Tested it ?? Give your review at #799

### CODE REVIEW

**Comment by Jai-JAP** [comment]
@Botspot

**Comment by Itai-Nelken** [comment]
@Botspot looks good to me

**Comment by Jai-JAP** [comment]
@Botspot

**Comment by Jai-JAP** [comment]
@Botspot

**Comment by Jai-JAP** [comment]
This is ready to merge @Botspot

**Comment by Jai-JAP** [comment]
Have you tested it?

**Comment by Jai-JAP** [comment]
Updated scripts for latest api functions
Tested working

**Comment by theofficialgman** [comment]
to avoid github DMCA and the controversy surrounding this project. I'm going to close this PR. keep in mind that true clean room decompilation projects have not been DMCA'd, while GTA III was...

as suggested by botspot, feel free to do this:

> Even if your app follows all of these guidelines, there still may be a reason we decide not to add it to the official Pi-Apps repository. If that happens, you can still take advantage of Pi-Apps's features by telling your users to import the zip file for your app.

**Pull request closed without merging**
