### PR TITLE
Clean machine1 patch 1

### PR DESCRIPTION
**Pull request by CleanMachine1**

### CODE REVIEW

**Comment by CleanMachine1** [comment]
This branch is an old one, with 36 or something commits behind, I am unaware if that affects it however worth another check from you if it does

**Comment by Itai-Nelken** [comment]
it doesn't affect anything right now, it will if the README.md is updated on the master branch of the main repo.

**Comment by CleanMachine1** [comment]
It doesn't fix anything - Yes 
Will it fix something in the future - Yes

I have been learning README for a few weeks now and while I still need to perfect writing it, it has a few easy to make errors.
The most common which I have and others have done is new line mistakes

Not adding new lines after content, meaning the new added lines overlap and make it look terrible

**Comment by Itai-Nelken** [comment]
I meant it doesn't affect anything to merge your outdated branch

**Comment by CleanMachine1** [comment]
oh..

**Comment by Itai-Nelken** [comment]
thanks for your explanation of new lines anyway!

**Comment by Botspot** [comment]
I'm closing this issue because the README has been updated since this PR was created.

@CleanMachine1 is welcome to update this PR with the latest README, but I don't see the point. If something breaks in the readme, somebody will usually notice within minutes and notify me about it.

**Comment by CleanMachine1** [comment]
No problem

**Pull request closed without merging**
