### PR TITLE
Fix typo in update-exclusion

### PR DESCRIPTION
**Pull request by Jai-JAP**

### CODE REVIEW

**Comment by CleanMachine1** [comment]
Documentation fixing - MY FAVOURITE :smile:

**Comment by Botspot** [comment]
Thanks for catching that.

This pull request will be marged, but beware that update-exclusion is stored in the `data/` directory. Consequently, it won't be updated on all pre-existing systems.

**Comment by Itai-Nelken** [comment]
> it won't be updated on all pre-existing systems.

it should, because it fixes the wine installing on twisterOS when updating..

**Comment by Botspot** [comment]
> > it won't be updated on all pre-existing systems.
> 
> it should, because it fixes the wine installing on twisterOS when updating..

This file is not modified directly **by the updater**. Therefore, changing this file in the repo now, won't change it for the people who already had this file. Make sense?
Nothing in the data directory is checked for updates. This is necessary in order to allow users to customize these files.

**Pull request merged**
