### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by derryktutt**
Made small improvements
(yes, amogos is real)

### CODE REVIEW

**Comment by Botspot** [comment]
AmogOS is also available for x86 PCs, but Pi-Apps is not. If we list AmogOS as "supported", then some users may get the false impression that Pi-Apps is supported on x86.
Can we get an expert opinion from @mobilegmYT ? :P

**Comment by mobilegmYT** [comment]
> AmogOS is also available for x86 PCs, but Pi-Apps is not. If we list AmogOS as "supported", then some users may get the false impression that Pi-Apps is supported on x86. Can we get an expert opinion from @mobilegmYT ? :P

I mean technically Pi Apps x86 is preinstalled...

**Comment by derryktutt** [comment]
The AmogOS github page says "Pi-Apps x86 for the x64 build." I will try it in a vm later today.

**Comment by derryktutt** [comment]
Yes, Pi-apps is there.

**Comment by Crilum** [comment]
> Yes, Pi-apps is there.

Are you on an arm build or a x86/x64 build?

**Comment by derryktutt** [comment]
Oh, I was using Arm.

**Comment by Botspot** [comment]
> I mean technically Pi Apps x86 is preinstalled...

But **_we_** don't support it. Not here, at least.

**Comment by Crilum** [comment]
> Oh, I was using Arm.


Did it have the real Pi-Apps, or the x86 version?

**Comment by derryktutt** [comment]
The raspberry pi version has the real one. AmogOS for the raspberry pi is
just Rasbian but it is among us themed.

**Comment by Crilum** [comment]
So we support AmogOS arm?

**Comment by derryktutt** [comment]
If you install AmogOS on the raspberry pi, from AmogOS.studio, Pi-apps is
pre-installed.

**Comment by derryktutt** [comment]
I used AmogOS on distrowatch, and took a screen recording. It has Pi-apps x86. I do not know if it works, because Distrowatch has no internet
[amogOS.mp4.zip](https://github.com/Botspot/pi-apps/files/7793919/amogOS.mp4.zip)
.

**Comment by Crilum** [comment]
Yeah, it was running x86_64 AmogOS, so..

**Comment by Crilum** [comment]
@mobilegmYT correct me if I'm wrong, Raspberry Pi AmogOS has Pi-Apps, and AmogOS x86 has Pi-Apps x86, right?

**Comment by derryktutt** [comment]
> @mobilegmYT correct me if I'm wrong, Raspberry Pi AmogOS has Pi-Apps, and AmogOS x86 has Pi-Apps x86, right?

That is correct.

**Comment by Crilum** [comment]
@Botspot I think we're good now..

**Pull request merged**
