### PR TITLE
Fixed Powerline Shell

### PR DESCRIPTION
**Pull request by open-sorcerer64**

### CODE REVIEW

**Comment by cycool29** [comment]
He copied [the install script](https://raw.githubusercontent.com/techcoder20/RPI-PowerlineShell-Installer/main/install.sh) and uninstall Starship Prompt before installing.

@open-sorcerer64  BTW, you should not uninstall apps without user permission.

**Comment by open-sorcerer64** [comment]
> What was wrong with the current script? (What did you fix?)

Starship and powerline can not be installed together on bash

**Comment by Botspot** [comment]
> Starship and powerline can not be installed together on bash

That makes sense. For transparency, I think that it would be better to notify the user about the problem, rather than secretly making changes which may confuse the user.
I suggest using an error message to notify the user that "another terminal theme is already installed. Please uninstall that one first" (see the conky app)

**Comment by theofficialgman** [comment]
> That makes sense. For transparency, I think that it would be better to notify the user about the problem, rather than secretly making changes which may confuse the user. I suggest using an error message to notify the user that "another terminal theme is already installed. Please uninstall that one first" (see the conky app)

on this note, it might be a good idea to make this a user error as well `User error: ` so that the upload log button is hidden

**Comment by open-sorcerer64** [comment]
Ok then, I will update the scripts! Also please check Starship while you guys are at it

**Comment by Botspot** [comment]
Any updates to this issue, @open-sorcerer64?

**Pull request closed without merging**
