### PR TITLE
add BlockBench

### LINKED ISSUE #792: BlockBench
Hey, I am a avid Minecrafter, and I would like to be able to use BlockBench (https://blockbench.net/) on the pi, as the webapp is very slow on a pi. Could you please consider trying to figure this out? 
Thx! ~Zipperoos

### PR DESCRIPTION
**Pull request by ryanfortner**
to close #792

### CODE REVIEW

**Comment by Botspot** [comment]
The menu launcher does not have an icon and is in the "Other" category. Can this be improved? I think it either belongs in the Programming or Graphics category.

**Comment by ryanfortner** [comment]
> The menu launcher does not have an icon and is in the "Other" category. Can this be improved? I think it either belongs in the Programming or Graphics category.

I believe these debs do have an icon... are you using the old ones? I repackaged into new debs with icon lines in the .desktop file. 

As for the category, it's assigned to the '3D modeler' section, maybe this isn't recognized on some systems. I'll change it to graphics.

**Comment by Botspot** [comment]
> I believe these debs do have an icon... are you using the old ones?

I used the exact code in this PR to install BlockBench.

**Comment by ryanfortner** [comment]
@Botspot could you try reinstalling either one of the debs please? (from the same link)

**Comment by cycool29** [comment]
The `Categories=Programming;` category won't work, `Categories=Development;IDE;` works for me.

**Comment by ryanfortner** [comment]
@Botspot @cycool29 hopefully this can be the last revision of the debs.. lol

I've changed the category in the desktop entry, as well as the links in the scripts, could you please test them again?

**Comment by cycool29** [comment]
> @Botspot @cycool29 hopefully this can be the last revision of the debs.. lol
> 
> I've changed the category in the desktop entry, as well as the links in the scripts, could you please test them again?

Launched well. But it seems outdated.

I tried to launch the latest `4.0.3` version with npm, launched well. 
I am trying to build the deb, will upload it here later.

**Comment by cycool29** [comment]
I have successfully compiled the deb, and added icon for Blockbench in taskbar!

armhf: https://transfer.sh/8a0dO0/blockbench_4.0.3_armhf.deb
arm64: Will upload soon...

**Comment by cycool29** [comment]
Just tested on both armhf and arm64, launched well. 

@ryanfortner Can you upload the debs to your raspbian-addons repository and also update the install scripts?

**Comment by ryanfortner** [comment]
> Just tested on both armhf and arm64, launched well.
> 
> @ryanfortner Can you upload the debs to your raspbian-addons repository and also update the install scripts?

Done.

@Botspot ready for merge to master.

**Comment by cycool29** [comment]
For future reference, here is the way I build the deb:
```bash
export version= #latest version on the release page
```

```bash
export NODE_OPTIONS=--openssl-legacy-provider
git clone https://github.com/JannisX11/blockbench.git
cd blockbench && npm install 
sed -i "s/icon:'icon.ico'/icon:'icon.png'/g" ./main.js #for taskbar icon
```
```bash
npx electron-builder --linux zip --armv7l 
#or
npx electron-builder --linux zip --arm64
```
```bash
wget https://github.com/JannisX11/blockbench/releases/download/v4.0.5/Blockbench_"$version".deb -O ../sample.deb
dpkg-deb -R ../sample.deb ../blockbench-deb
rm -f ../sample.deb
cp dist/Blockbench*.zip ../blockbench-deb/opt
rm -rf ../blockbench-deb/opt/Blockbench
cd ../blockbench-deb/opt
unzip ./*zip -d Blockbench
rm *zip
cp ../../blockbench/icon.png ./Blockbench
```
```bash
sed -i 's/amd64/armhf/g' ../DEBIAN/control
cd ../..
dpkg-deb -b ./blockbench-deb blockbench_"$version"_armhf.deb
#or
sed -i 's/amd64/arm64/g' ../DEBIAN/control
cd ../..
dpkg-deb -b ./blockbench-deb blockbench_"$version"_arm64.deb

```

**Comment by ryanfortner** [comment]
@cycool29 I tried to set up a github actions workflow [here](https://github.com/ryanfortner/blockbench-arm/blob/master/.github/workflows/Build-arm64.yml), but during the `npx electron-builder --linux zip --arm64` command, I get this error, even though the GH_TOKEN is set...

```
  ⨯ GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
```

**Comment by cycool29** [comment]
> @cycool29 I tried to set up a github actions workflow [here](https://github.com/ryanfortner/blockbench-arm/blob/master/.github/workflows/Build-arm64.yml), but during the `npx electron-builder --linux zip --arm64` command, I get this error, even though the GH_TOKEN is set...
> 
> ```
>   ⨯ GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
> ```

I have opened a [PR](https://github.com/ryanfortner/blockbench-arm/pull/1) on your repo to fix that.

**Pull request merged**
