### PR TITLE
Update 32-bit Bedrock to latest version.

### PR DESCRIPTION
**Pull request by mobilegmYT**

### CODE REVIEW

**Comment by Botspot** [comment]
Can we move the appimage to /home/pi or /opt? /usr/bin or /usr/local/bin are both abnormal places for appimages.

Thank you.

**Comment by mobilegmYT** [comment]
> Can we move the appimage to /home/pi or /opt? /usr/bin or /usr/local/bin are both abnormal places for appimages.
> 
> Thank you.

ah ok 1 sec

**Comment by mobilegmYT** [comment]
@Botspot Done

**Comment by mobilegmYT** [comment]
Also did the same for the 64-bit pull reqest.

**Comment by Botspot** [comment]
Let's name both appimages the same, and **make sure the uninstall script removes them!**

**Comment by mobilegmYT** [comment]
oop

**Comment by mobilegmYT** [comment]
wait no 1 sec

**Comment by mobilegmYT** [comment]
@Botspot I think that should be all. Can you review the changes?

**Pull request merged**
